import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import StatCard from '../components/StatCard';
import StatusBadge from '../components/StatusBadge';
import LeadActions from '../components/LeadActions';
import {useAuth} from '../context/AuthContext';
import {Users,UserRoundCheck,CalendarClock,CircleAlert,UserPlus,ArrowRight,IndianRupee,BadgeCheck,WalletCards,HandCoins,PackageCheck,ReceiptText,TrendingUp,UserX} from 'lucide-react';
import {SortableTh,useSortedRows} from '../components/SortableTable';

function dayBounds(){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);return{start:start.toISOString(),end:end.toISOString()};}
function periodBounds(period,from,to){const today=new Date();today.setHours(0,0,0,0);let start=new Date(today),end=new Date(today);end.setDate(end.getDate()+1);if(period==='yesterday'){start.setDate(start.getDate()-1);end=new Date(today);}else if(['7','30','90'].includes(period))start.setDate(start.getDate()-(Number(period)-1));else if(period==='custom'){start=from?new Date(`${from}T00:00:00`):today;end=to?new Date(`${to}T00:00:00`):new Date(start);end.setDate(end.getDate()+1);}return{start:start.toISOString(),end:end.toISOString()};}
function fmt(value){return value?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-';}
const money=value=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const leadUrl=params=>`/leads?${new URLSearchParams(params).toString()}`;
const orderUrl=(metric,range)=>`${metric==='invoice'?'/tax-invoices':'/purchase-orders'}?${new URLSearchParams({metric,from:range.start,to:range.end}).toString()}`;

export default function Dashboard(){
  const {user,can}=useAuth();const [data,setData]=useState({stats:{},schedule:[],analytics:{},recentOrders:[]}),[error,setError]=useState(''),[period,setPeriod]=useState('30'),[custom,setCustom]=useState({from:'',to:''});
  const scheduleSort=useSortedRows(data.schedule,'next_followup_at','asc');const today=useMemo(dayBounds,[]);const range=useMemo(()=>periodBounds(period,custom.from,custom.to),[period,custom]);
  useEffect(()=>{const query=new URLSearchParams({start:today.start,end:today.end,analyticsStart:range.start,analyticsEnd:range.end});api(`/dashboard?${query}`).then(setData).catch(e=>setError(e.message));},[today.start,today.end,range.start,range.end]);
  const s=data.stats,a=data.analytics,periodLabel=period==='today'?'Today':period==='yesterday'?'Yesterday':period==='custom'?'Custom range':`Last ${period} days`;
  return <>
    <div className="page-heading dashboard-heading"><div><span className="eyebrow">Overview</span><h1>Good day, {user.name.split(' ')[0]}</h1><p>Sales activity, collections and pending work in one place.</p></div><Link to="/leads" className="btn btn-primary">View all leads <ArrowRight size={16}/></Link></div>
    {error&&<div className="alert error">{error}</div>}
    <div className="stats-grid dashboard-lead-stats">
      <Link className="stat-link" to="/leads"><StatCard icon={Users} label={user.role==='ADMIN'?'Total Leads':'My Leads'} value={s.total} hint="View all records"/></Link>
      <Link className="stat-link" to={leadUrl({pipeline:'open'})}><StatCard icon={UserRoundCheck} tone="blue" label="Open Leads" value={s.open} hint="View active pipeline"/></Link>
      <Link className="stat-link" to={leadUrl({followup:'today',start:today.start,end:today.end})}><StatCard icon={CalendarClock} tone="gold" label="Due Today" value={s.today} hint="View today's follow-ups"/></Link>
      <Link className="stat-link" to={leadUrl({followup:'overdue',start:today.start})}><StatCard icon={CircleAlert} tone="red" label="Overdue" value={s.overdue} hint="View overdue leads"/></Link>
      {user.role==='ADMIN'&&<Link className="stat-link" to={leadUrl({assignedTo:'unassigned'})}><StatCard icon={UserPlus} tone="violet" label="Unassigned" value={s.unassigned} hint="Assign an owner"/></Link>}
      <Link className="stat-link" to="/not-interested-leads"><StatCard icon={UserX} tone="muted" label="Not Interested" value={s.notInterested||0} hint="View archived leads"/></Link>
    </div>
    {can('SECTION_DASHBOARD_REVENUE')&&<section className="analytics-section">
      <div className="analytics-heading"><div><span className="eyebrow">Business analytics</span><h2>Revenue & order performance</h2><p>Calculated from purchase orders, invoices and recorded payments.</p></div><div className="analytics-period"><select aria-label="Analytics period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="custom">Custom range</option></select>{period==='custom'&&<><input aria-label="From date" type="date" value={custom.from} max={custom.to||undefined} onClick={e=>e.currentTarget.showPicker?.()} onChange={e=>setCustom({...custom,from:e.target.value})}/><span>to</span><input aria-label="To date" type="date" value={custom.to} min={custom.from||undefined} onClick={e=>e.currentTarget.showPicker?.()} onChange={e=>setCustom({...custom,to:e.target.value})}/></>}<em>{periodLabel}</em></div></div>
      <div className="revenue-grid"><Metric to={orderUrl('orders',range)} icon={BadgeCheck} tone="navy" label="Final Orders" value={a.final_orders||0} hint="View confirmed orders"/><Metric to={orderUrl('orders',range)} icon={IndianRupee} tone="gold" label="Order Value" value={money(a.order_value)} hint="View order records"/><Metric to={orderUrl('received',range)} icon={WalletCards} tone="green" label="Payment Received" value={money(a.payment_received)} hint={`${a.collection_rate||0}% collected`}/><Metric to={orderUrl('pending',range)} icon={HandCoins} tone="red" label="Pending Payment" value={money(a.pending_payment)} hint="View outstanding orders"/><Metric to={leadUrl({sampleFrom:range.start,sampleTo:range.end})} icon={PackageCheck} tone="violet" label="Samples Sent" value={a.samples_sent||0} hint="View matching leads"/><Metric to={orderUrl('invoice',range)} icon={ReceiptText} tone="cyan" label="Invoices Created" value={a.invoices_created||0} hint={`${money(a.invoiced_value)} invoiced`}/><Metric to={orderUrl('orders',range)} icon={TrendingUp} tone="teal" label="Average Order" value={money(a.average_order_value)} hint="View order records"/></div>
    </section>}
    {can('SECTION_DASHBOARD_REVENUE')&&<section className="panel"><div className="panel-head"><div><h2>Recent orders</h2><p>{data.recentOrders.length} orders in {periodLabel.toLowerCase()}.</p></div>{can('PAGE_ORDERS')&&<Link className="text-link" to="/orders">PO & Invoices <ArrowRight size={14}/></Link>}</div>{data.recentOrders.length?<div className="table-wrap"><table className="dashboard-orders"><thead><tr><th>PO Number</th><th>Client</th>{user.role==='ADMIN'&&<th>Owner</th>}<th>Order Value</th><th>Received</th><th>Pending</th><th>Invoice</th><th>Created</th></tr></thead><tbody>{data.recentOrders.map(order=><tr key={order.id}><td>{can('PAGE_ORDERS')?<Link className="lead-link" to={`/purchase-orders/${order.id}`}>{order.po_number}</Link>:order.po_number}</td><td>{can('PAGE_LEADS')?<Link className="lead-link" to={`/leads/${order.lead_id}`}>{order.contact_name}</Link>:<strong>{order.contact_name}</strong>}<span className="cell-sub">{order.company_name||'Individual lead'}</span></td>{user.role==='ADMIN'&&<td>{order.owner_name||'Unassigned'}</td>}<td>{money(order.total)}</td><td className="analytics-positive">{money(order.advance_amount)}</td><td className={Number(order.pending_amount)>0?'analytics-negative':''}>{money(order.pending_amount)}</td><td>{order.invoice_number?`#${order.invoice_number}`:'Not created'}</td><td>{fmt(order.created_at)}</td></tr>)}</tbody></table></div>:<div className="empty">No orders found for this period.</div>}</section>}
    {can('SECTION_DASHBOARD_FOLLOWUPS')&&<section className="panel"><div className="panel-head"><div><h2>Today's follow-ups</h2><p>Your scheduled customer conversations, sorted by time.</p></div>{can('PAGE_FOLLOWUPS')&&<Link className="text-link" to="/followups">See all <ArrowRight size={14}/></Link>}</div>{!data.schedule.length?<div className="empty">No follow-ups scheduled for today.</div>:<div className="table-wrap"><table><thead><tr><SortableTh label="Time" field="next_followup_at" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/><SortableTh label="Lead" field="contact_name" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/><SortableTh label="Requirement" field="requirement" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/>{user.role==='ADMIN'&&<SortableTh label="Owner" field="assigned_name" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/>}<SortableTh label="Status" field="status" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/><th>Action</th></tr></thead><tbody>{scheduleSort.rows.map(lead=><tr key={lead.id}><td><strong>{fmt(lead.next_followup_at)}</strong></td><td>{can('PAGE_LEADS')?<Link to={`/leads/${lead.id}`} className="lead-link">{lead.contact_name}</Link>:<strong>{lead.contact_name}</strong>}<span className="cell-sub">{lead.company_name||lead.phone||'-'}</span></td><td>{lead.requirement||'-'}</td>{user.role==='ADMIN'&&<td>{lead.assigned_name||<span className="danger-text">Unassigned</span>}</td>}<td><StatusBadge status={lead.status}/></td><td><LeadActions phone={lead.phone} compact/></td></tr>)}</tbody></table></div>}</section>}
  </>;
}
function Metric({icon:Icon,label,value,hint,tone='',to}){return <Link to={to} className={`revenue-card ${tone}`}><span><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong><em>{hint}</em></div></Link>}
