import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import StatCard from '../components/StatCard';
import StatusBadge from '../components/StatusBadge';
import LeadActions from '../components/LeadActions';
import {Activity,ArrowRight,BadgeCheck,CalendarClock,CircleAlert,CircleDot,ClipboardCheck,HandCoins,IndianRupee,PackageCheck,ReceiptText,RotateCcw,Trophy,UserPlus,UserRoundCheck,Users,UserX} from 'lucide-react';
import {useAuth} from '../context/AuthContext';
import {SortableTh,useSortedRows} from '../components/SortableTable';

function dayBounds(){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);return{start:start.toISOString(),end:end.toISOString()};}
function periodBounds(period,from,to){const today=new Date();today.setHours(0,0,0,0);let start=new Date(today),end=new Date(today);end.setDate(end.getDate()+1);if(period==='all'){start=new Date(0);}else if(period==='yesterday'){start.setDate(start.getDate()-1);end=new Date(today);}else if(period==='month'){start.setDate(1);}else if(['7','30','90'].includes(period))start.setDate(start.getDate()-(Number(period)-1));else if(period==='custom'){start=from?new Date(`${from}T00:00:00`):today;end=to?new Date(`${to}T00:00:00`):new Date(start);end.setDate(end.getDate()+1);}return{start:start.toISOString(),end:end.toISOString()};}
function fmt(value){return value?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-';}
const money=value=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const leadUrl=params=>`/leads?${new URLSearchParams(params).toString()}`;
const orderUrl=(metric,range)=>`${metric==='invoice'?'/tax-invoices':'/purchase-orders'}?${new URLSearchParams({metric,from:range.start,to:range.end}).toString()}`;

export default function Dashboard(){
  const {user,can}=useAuth();
  const [data,setData]=useState({stats:{},schedule:[],team:[],analytics:{},recentOrders:[]});
  const [error,setError]=useState('');
  const [period,setPeriod]=useState('all');
  const [custom,setCustom]=useState({from:'',to:''});
  const today=useMemo(dayBounds,[]);
  const range=useMemo(()=>periodBounds(period,custom.from,custom.to),[period,custom]);
  const scheduleSort=useSortedRows(data.schedule,'next_followup_at','asc');
  const periodLabel=period==='all'?'All time':period==='today'?'Today':period==='yesterday'?'Yesterday':period==='month'?'Current month':period==='custom'?'Custom range':`Last ${period} days`;
  const cohort={createdFrom:range.start,createdTo:range.end};
  const cohortLeadUrl=filters=>leadUrl({...cohort,...filters});
  const teamUrl=(userId,filters)=>cohortLeadUrl({assignedTo:userId,...filters});
  useEffect(()=>{const query=new URLSearchParams({start:today.start,end:today.end,leadStart:range.start,leadEnd:range.end,analyticsStart:range.start,analyticsEnd:range.end});api(`/dashboard?${query}`).then(setData).catch(error=>setError(error.message));},[today.start,today.end,range.start,range.end]);

  const s=data.stats,a=data.analytics;
  return <>
    <div className="page-heading dashboard-heading"><div><span className="eyebrow">Sales workspace</span><h1>Good day, {user.name.split(' ')[0]}</h1><p>Start with new leads, complete today’s work, then clear overdue follow-ups.</p></div><Link to={cohortLeadUrl({pipeline:'active'})} className="btn btn-primary">Open active leads <ArrowRight size={16}/></Link></div>
    {error&&<div className="alert error">{error}</div>}

    <section className="dashboard-lead-overview"><div className="dashboard-section-title"><div><span className="eyebrow">Lead command centre</span><h2>{user.role==='ADMIN'?'Team pipeline':'My pipeline'}</h2><p>Lead counts are for leads received in the selected period. Due and overdue remain today’s action queue.</p></div>{user.role==='ADMIN'&&<DashboardPeriod period={period} setPeriod={setPeriod} custom={custom} setCustom={setCustom} label={periodLabel}/>}</div>
      <div className="stats-grid dashboard-lead-stats">
        <Link className="stat-link" to={cohortLeadUrl({includeArchived:'1'})}><StatCard icon={Users} label={user.role==='ADMIN'?'Total Leads':'My Total Leads'} value={s.total||0} hint={`Received ${periodLabel.toLowerCase()}`}/></Link>
        <Link className="stat-link" to={cohortLeadUrl({pipeline:'active'})}><StatCard icon={UserRoundCheck} tone="blue" label="Active Leads" value={s.active||0} hint="Excludes won, lost & not interested"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({pipeline:'new'})}><StatCard icon={CircleDot} tone="violet" label="New / Untouched" value={s.newLeads||0} hint="No follow-up logged yet"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({pipeline:'working'})}><StatCard icon={ClipboardCheck} tone="teal" label="Working Leads" value={s.working||0} hint="At least one follow-up saved"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({work:'today',start:today.start,end:today.end})}><StatCard icon={Activity} tone="green" label="Worked Today" value={s.workedToday||0} hint="Unique leads with follow-up saved today"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({followup:'today',start:today.start,end:today.end})}><StatCard icon={CalendarClock} tone="gold" label="Due Today" value={s.dueToday||0} hint="Scheduled for today"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({followup:'overdue',start:today.start})}><StatCard icon={CircleAlert} tone="red" label="Overdue" value={s.overdue||0} hint="Past next follow-up date"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({status:'NOT_INTERESTED',includeArchived:'1'})}><StatCard icon={UserX} tone="muted" label="Not Interested" value={s.notInterested||0} hint="Archived leads"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({status:'CLOSED_LOST',includeArchived:'1'})}><StatCard icon={UserX} tone="red" label="Closed Lost" value={s.closedLost||0} hint="Lost opportunities"/></Link>
        <Link className="stat-link" to={cohortLeadUrl({status:'CLOSED_WON'})}><StatCard icon={Trophy} tone="green" label="Closed Won" value={s.closedWon||0} hint="Converted opportunities"/></Link>
        {user.role==='ADMIN'&&<Link className="stat-link" to={cohortLeadUrl({assignedTo:'unassigned',pipeline:'active'})}><StatCard icon={UserPlus} tone="violet" label="Unassigned" value={s.unassigned||0} hint="Needs an owner"/></Link>}
      </div>
    </section>

    {user.role==='ADMIN'&&<section className="panel team-performance-panel"><div className="panel-head"><div><span className="eyebrow">Manager view</span><h2>Team execution</h2><p>{periodLabel} lead cohort. Worked Today is unique active leads with a follow-up saved today.</p></div></div><div className="table-wrap"><table className="team-performance-table"><thead><tr><th>Team member</th><th>Active</th><th>New</th><th>Working</th><th>Due today</th><th>Overdue</th><th>Worked today</th><th>Won</th></tr></thead><tbody>{data.team.map(member=><tr key={member.user_id}><td><strong>{member.name}</strong></td><td><Link to={teamUrl(member.user_id,{pipeline:'active'})}>{member.active}</Link></td><td><Link to={teamUrl(member.user_id,{pipeline:'new'})}>{member.newLeads}</Link></td><td><Link to={teamUrl(member.user_id,{pipeline:'working'})}>{member.working}</Link></td><td><Link to={teamUrl(member.user_id,{followup:'today',start:today.start,end:today.end})}>{member.dueToday}</Link></td><td><Link to={teamUrl(member.user_id,{followup:'overdue',start:today.start})}>{member.overdue}</Link></td><td><Link to={teamUrl(member.user_id,{work:'today',start:today.start,end:today.end})}>{member.workedToday}</Link></td><td><Link to={teamUrl(member.user_id,{status:'CLOSED_WON'})}>{member.closedWon}</Link></td></tr>)}</tbody></table></div>{!data.team.length&&<div className="empty">No active team members found.</div>}</section>}

    {can('SECTION_DASHBOARD_REVENUE')&&<section className="analytics-section"><div className="analytics-heading"><div><span className="eyebrow">Business analytics</span><h2>Revenue & order performance</h2><p>For leads received in {periodLabel.toLowerCase()}, with documents created in the same period.</p></div><div className="analytics-period"><em>{periodLabel}</em></div></div><div className="revenue-grid"><Metric to={orderUrl('orders',range)} icon={BadgeCheck} tone="navy" label="Final Orders" value={a.final_orders||0} hint="View confirmed orders"/><Metric to={orderUrl('orders',range)} icon={IndianRupee} tone="gold" label="Order Value" value={money(a.order_value)} hint="View order records"/><Metric to={orderUrl('received',range)} icon={Activity} tone="green" label="Payment Received" value={money(a.payment_received)} hint={`${a.collection_rate||0}% collected`}/><Metric to={orderUrl('pending',range)} icon={HandCoins} tone="red" label="Pending Payment" value={money(a.pending_payment)} hint="View outstanding orders"/><Metric to={cohortLeadUrl({sampleFrom:range.start,sampleTo:range.end})} icon={PackageCheck} tone="violet" label="Samples Sent" value={a.samples_sent||0} hint="View matching leads"/><Metric to={orderUrl('invoice',range)} icon={ReceiptText} tone="cyan" label="Invoices Created" value={a.invoices_created||0} hint={`${money(a.invoiced_value)} invoiced`}/><Metric to={orderUrl('orders',range)} icon={CircleDot} tone="teal" label="Average Order" value={money(a.average_order_value)} hint="View order records"/></div></section>}

    {can('SECTION_DASHBOARD_REVENUE')&&<section className="panel"><div className="panel-head"><div><h2>Recent orders</h2><p>{data.recentOrders.length} orders in {periodLabel.toLowerCase()}.</p></div>{can('PAGE_ORDERS')&&<Link className="text-link" to="/orders">PO & Invoices <ArrowRight size={14}/></Link>}</div>{data.recentOrders.length?<div className="table-wrap"><table className="dashboard-orders"><thead><tr><th>PO Number</th><th>Client</th>{user.role==='ADMIN'&&<th>Owner</th>}<th>Order Value</th><th>Received</th><th>Pending</th><th>Invoice</th><th>Created</th></tr></thead><tbody>{data.recentOrders.map(order=><tr key={order.id}><td><Link className="lead-link" to={`/purchase-orders/${order.id}`}>{order.po_number}</Link></td><td><Link className="lead-link" to={`/leads/${order.lead_id}`}>{order.contact_name}</Link><span className="cell-sub">{order.company_name||'Individual lead'}</span></td>{user.role==='ADMIN'&&<td>{order.owner_name||'Unassigned'}</td>}<td>{money(order.total)}</td><td className="analytics-positive">{money(order.advance_amount)}</td><td className="analytics-negative">{money(order.pending_amount)}</td><td>{order.invoice_number?`#${order.invoice_number}`:'Not created'}</td><td>{fmt(order.created_at)}</td></tr>)}</tbody></table></div>:<div className="empty">No orders found for this period.</div>}</section>}

    {can('SECTION_DASHBOARD_FOLLOWUPS')&&<section className="panel"><div className="panel-head"><div><h2>Today’s follow-ups</h2><p>For leads received in {periodLabel.toLowerCase()}, sorted by time.</p></div>{can('PAGE_FOLLOWUPS')&&<Link className="text-link" to="/followups">See all <ArrowRight size={14}/></Link>}</div>{!data.schedule.length?<div className="empty">No follow-ups scheduled for today.</div>:<div className="table-wrap"><table><thead><tr><SortableTh label="Time" field="next_followup_at" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/><SortableTh label="Lead" field="contact_name" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/><SortableTh label="Requirement" field="requirement" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/>{user.role==='ADMIN'&&<SortableTh label="Owner" field="assigned_name" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/>}<SortableTh label="Status" field="status" sort={scheduleSort.sort} onSort={scheduleSort.toggle}/><th>Action</th></tr></thead><tbody>{scheduleSort.rows.map(lead=><tr key={lead.id}><td><strong>{fmt(lead.next_followup_at)}</strong></td><td><Link to={`/leads/${lead.id}`} className="lead-link">{lead.contact_name}</Link><span className="cell-sub">{lead.company_name||lead.phone||'-'}</span></td><td>{lead.requirement||'-'}</td>{user.role==='ADMIN'&&<td>{lead.assigned_name||<span className="danger-text">Unassigned</span>}</td>}<td><StatusBadge status={lead.status}/></td><td><LeadActions phone={lead.phone} compact/></td></tr>)}</tbody></table></div>}</section>}
  </>;
}

function DashboardPeriod({period,setPeriod,custom,setCustom,label}){const reset=()=>{setPeriod('all');setCustom({from:'',to:''});};return <div className="dashboard-period"><label>Lead period<select aria-label="Lead period" value={period} onChange={event=>setPeriod(event.target.value)}><option value="all">All time</option><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="month">Current month</option><option value="custom">Custom range</option></select></label>{period==='custom'&&<><label>From<input aria-label="From date" type="date" value={custom.from} max={custom.to||undefined} onClick={event=>event.currentTarget.showPicker?.()} onChange={event=>setCustom({...custom,from:event.target.value})}/></label><label>To<input aria-label="To date" type="date" value={custom.to} min={custom.from||undefined} onClick={event=>event.currentTarget.showPicker?.()} onChange={event=>setCustom({...custom,to:event.target.value})}/></label></>}<em>{label}</em>{period!=='all'&&<button type="button" className="dashboard-period-reset" title="Reset to all time" onClick={reset}><RotateCcw size={14}/>Reset</button>}</div>}
function Metric({icon:Icon,label,value,hint,tone='',to}){return <Link to={to} className={`revenue-card ${tone}`}><span><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong><em>{hint}</em></div></Link>;}
