import {useEffect,useState} from 'react';
import {AlertTriangle,FileText,ReceiptText,RefreshCw,Trash2,Users} from 'lucide-react';
import {api} from '../api';

const actions=[
  {target:'INVOICES',title:'Tax Invoices',icon:ReceiptText,color:'amber',phrase:'RESET INVOICES',description:'Deletes all tax invoices, resets invoice number to 10001 and reopens converted POs. Manual-invoice records are also removed.',counts:['taxInvoices']},
  {target:'ORDERS',title:'POs & Invoices',icon:FileText,color:'blue',phrase:'RESET ORDERS',description:'Deletes every purchase order and tax invoice. Manual PO/invoice placeholder leads are removed. Invoice and PO numbering restart.',counts:['purchaseOrders','taxInvoices']},
  {target:'LEADS',title:'All Leads & Documents',icon:Users,color:'red',phrase:'RESET LEADS',description:'Deletes leads, follow-ups, notifications, purchase orders and invoices. Sheet history is retained, so old Sheet rows are not imported again.',counts:['leads','followups','purchaseOrders','taxInvoices']},
  {target:'ALL',title:'Complete Test Data Reset',icon:Trash2,color:'dark',phrase:'RESET ALL DATA',description:'Deletes all transactional data and Sheet sync history. Auto-sync is paused to prevent old Sheet rows from returning immediately.',counts:['leads','followups','purchaseOrders','taxInvoices','sheetRows','syncLogs']}
];
const labels={leads:'Leads',followups:'Follow-ups',purchaseOrders:'Purchase Orders',taxInvoices:'Tax Invoices',notifications:'Notifications',sheetRows:'Tracked Sheet Rows',syncLogs:'Sync Logs'};

export default function DataReset(){
  const [counts,setCounts]=useState({});const [selected,setSelected]=useState(null);const [confirmation,setConfirmation]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function load(){try{const data=await api('/maintenance');setCounts(data.counts);}catch(e){setError(e.message);}}useEffect(()=>{load();},[]);
  async function reset(){if(!selected||confirmation!==selected.phrase)return;setBusy(true);setError('');try{await api('/maintenance/reset',{method:'POST',body:JSON.stringify({target:selected.target,confirmation})});setSelected(null);setConfirmation('');await load();window.dispatchEvent(new Event('lead-notifications:refresh'));}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <><div className="page-heading"><div><span className="eyebrow">Admin Tools</span><h1>Data Reset</h1><p>Clear testing records safely before the CRM goes live.</p></div></div>{error&&<div className="alert error">{error}</div>}<div className="reset-warning"><AlertTriangle size={20}/><div><strong>Deleted data cannot be recovered</strong><p>Take an export or database backup first. Users, permissions, masters, brand settings and integration configuration are never deleted here.</p></div></div><section className="reset-counts">{Object.entries(labels).map(([key,label])=><div key={key}><span>{label}</span><strong>{Number(counts[key]||0).toLocaleString('en-IN')}</strong></div>)}</section><div className="reset-grid">{actions.map(action=>{const Icon=action.icon;return <section className={`panel reset-card ${action.color}`} key={action.target}><div className="reset-card-icon"><Icon size={19}/></div><h2>{action.title}</h2><p>{action.description}</p><div className="reset-impact">{action.counts.map(key=><span key={key}>{labels[key]} <b>{counts[key]||0}</b></span>)}</div><button className="btn btn-danger full" disabled={!action.counts.some(key=>counts[key])} onClick={()=>{setSelected(action);setConfirmation('');}}><Trash2 size={14}/>Clear {action.title}</button></section>})}</div>{selected&&<div className="reset-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)setSelected(null);}}><section className="reset-modal" role="dialog" aria-modal="true"><div className="reset-confirm-icon"><AlertTriangle size={24}/></div><h2>Confirm {selected.title} reset</h2><p>{selected.description}</p><label>Type <strong>{selected.phrase}</strong> to continue<input autoFocus value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder={selected.phrase}/></label><footer><button className="btn btn-ghost" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button><button className="btn btn-danger" disabled={busy||confirmation!==selected.phrase} onClick={reset}>{busy?<><RefreshCw className="spin" size={14}/>Clearing...</>:<><Trash2 size={14}/>Delete permanently</>}</button></footer></section></div>}</>;
}
