import { useEffect, useState } from 'react';
import { api } from '../api';
import {ArrowDown,ArrowUp,FileSpreadsheet,Upload,UserRoundCheck} from 'lucide-react';

export default function ImportLeads(){
  const [users,setUsers]=useState([]); const [file,setFile]=useState(null); const [assignedTo,setAssignedTo]=useState('');const [assignmentMode,setAssignmentMode]=useState('FIXED');const [assignmentUserIds,setAssignmentUserIds]=useState([]);const [leadsPerUser,setLeadsPerUser]=useState(1); const [result,setResult]=useState(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{api('/users?all=1').then(d=>setUsers(d.users));},[]);
  async function submit(e){e.preventDefault();if(!file)return;setBusy(true);setError('');setResult(null);try{const fd=new FormData();fd.append('file',file);fd.append('assignmentMode',assignmentMode);fd.append('leadsPerUser',String(leadsPerUser));fd.append('assignmentUserIds',JSON.stringify(assignmentUserIds));if(assignmentMode==='FIXED'&&assignedTo)fd.append('assignedTo',assignedTo);const d=await api('/leads/actions/import',{method:'POST',body:fd});setResult(d);}catch(e){setError(e.message);}finally{setBusy(false);}}
  const activeUsers=users.filter(user=>user.active);const selectedUsers=assignmentUserIds.map(id=>activeUsers.find(user=>user.id===id)).filter(Boolean);function toggleUser(id){setAssignmentUserIds(value=>value.includes(id)?value.filter(userId=>userId!==id):[...value,id]);}function moveUser(index,direction){setAssignmentUserIds(value=>{const ids=[...value],next=index+direction;if(next<0||next>=ids.length)return value;[ids[index],ids[next]]=[ids[next],ids[index]];return ids;});}
  return <><div className="page-heading"><div><h1>Import Leads</h1><p>Upload Excel or CSV and optionally assign all imported leads to one salesperson.</p></div><a className="btn btn-ghost" href="/sample-leads.csv" download>Download sample CSV</a></div>
  <div className="import-layout"><section className="panel import-card"><div className="integration-title"><div className="integration-logo"><FileSpreadsheet size={22}/></div><div><h2>Upload Lead File</h2><p>Excel or CSV · Standard column mapping · Duplicate-safe import</p></div></div>{error&&<div className="alert error">{error}</div>}{result&&<div className="alert success"><strong>Import completed</strong><span>{result.imported} of {result.totalRows} rows imported · {result.skipped} skipped</span>{result.assignedUsers?.length>0&&<small>{result.assignedUsers.map(item=>`${item.name}: ${item.count}`).join(' · ')}</small>}</div>}
  <form className="form-stack" onSubmit={submit}><label>Excel / CSV File<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><div className="import-assignment-fields"><label>Assignment Method<select value={assignmentMode} onChange={e=>setAssignmentMode(e.target.value)}><option value="FIXED">Single user</option><option value="ROUND_ROBIN">Automatic rotation</option></select></label>{assignmentMode==='FIXED'&&<label>Assign imported leads to<select value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}><option value="">Keep unassigned</option>{activeUsers.map(user=><option value={user.id} key={user.id}>{user.name}</option>)}</select></label>}</div>{assignmentMode==='ROUND_ROBIN'&&<section className="assignment-builder"><div className="assignment-head"><div><strong><UserRoundCheck size={16}/> Import assignment rotation</strong><span>Select users and arrange the assignment sequence.</span></div><label>Leads per user<input type="number" min="1" max="1000" value={leadsPerUser} onChange={e=>setLeadsPerUser(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="assignment-users">{activeUsers.map(user=><button type="button" className={assignmentUserIds.includes(user.id)?'selected':''} key={user.id} onClick={()=>toggleUser(user.id)}><i>{assignmentUserIds.indexOf(user.id)+1||'+'}</i><span>{user.name}<small>{user.designation||user.role}</small></span></button>)}</div>{selectedUsers.length>0&&<div className="assignment-order">{selectedUsers.map((user,index)=><div key={user.id}><b>{index+1}</b><span>{user.name}<small>{leadsPerUser} lead{Number(leadsPerUser)===1?'':'s'}, then next user</small></span><button type="button" title="Move up" disabled={!index} onClick={()=>moveUser(index,-1)}><ArrowUp size={14}/></button><button type="button" title="Move down" disabled={index===selectedUsers.length-1} onClick={()=>moveUser(index,1)}><ArrowDown size={14}/></button></div>)}</div>}<p className="assignment-preview">Pattern: {selectedUsers.length?selectedUsers.map(user=>`${user.name} × ${leadsPerUser}`).join(' → ')+' → repeat':'Select at least one user'}</p></section>}<button className="btn btn-primary" disabled={busy||(assignmentMode==='ROUND_ROBIN'&&!assignmentUserIds.length)}><Upload size={15}/>{busy?'Importing...':'Import Leads'}</button></form>
  {result?.errors?.length>0&&<div className="error-list"><strong>Row issues</strong>{result.errors.map((e,i)=><span key={i}>{e}</span>)}</div>}</section>
  <section className="panel"><h2>Standard Lead Columns</h2><div className="column-list">{['Name *','Email','Phone *','Company','Quantity','Box Size','Budget','Message','Date'].map(x=><span key={x}>{x}</span>)}</div><p className="muted">Use this same format for Excel/CSV import and Google Sheet sync. Budget is saved as per-box budget; estimated value is calculated from Quantity × Budget. Phone numbers may include +91, spaces or line breaks.</p><div className="import-rule"><strong>How rotation works</strong><p>With 1 lead per user: User A → User B → User C. With 2: A → A → B → B → C → C. Duplicate or invalid rows do not use a user's turn.</p></div></section></div></>;
}
