import {useEffect,useMemo,useState} from 'react';
import {api} from '../api';
import {ArrowDown,ArrowUp,Cable,CheckCircle2,Clock3,ExternalLink,FileSpreadsheet,RefreshCw,Save,ShieldCheck,TriangleAlert,UserRoundCheck} from 'lucide-react';

const empty={name:'Google Ads Leads',sheetUrl:'',gid:'0',enabled:false,intervalMinutes:5,defaultSource:'Google Ads',assignedTo:'',assignmentMode:'FIXED',assignmentUserIds:[],leadsPerUser:1,mapping:{}};
const dateTime=value=>value?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value.endsWith?.('Z')?value:`${value}Z`)):'Never';

export default function Integrations(){
  const [form,setForm]=useState(empty);const [fields,setFields]=useState([]);const [headers,setHeaders]=useState([]);const [samples,setSamples]=useState([]);const [logs,setLogs]=useState([]);const [users,setUsers]=useState([]);const [error,setError]=useState('');const [testing,setTesting]=useState(false);const [saving,setSaving]=useState(false);const [syncing,setSyncing]=useState(false);const [saved,setSaved]=useState(null);
  async function load(){try{const [data,userData]=await Promise.all([api('/integrations/google-sheet'),api('/users')]);setFields(data.fields);setLogs(data.logs);setSaved(data.integration);if(data.integration){setForm({name:data.integration.name,sheetUrl:data.integration.sheet_url,gid:data.integration.gid,enabled:data.integration.enabled,intervalMinutes:data.integration.interval_minutes,defaultSource:data.integration.default_source,assignedTo:data.integration.assigned_to||'',assignmentMode:data.integration.assignment_mode||'FIXED',assignmentUserIds:data.integration.assignmentUserIds||[],leadsPerUser:data.integration.leads_per_user||1,mapping:data.integration.mapping||{}});setHeaders(value=>value.length?value:[...new Set(Object.values(data.integration.mapping||{}).filter(Boolean))]);}setUsers(userData.users);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[]);
  async function preview(){setTesting(true);setError('');try{const data=await api('/integrations/google-sheet/preview',{method:'POST',silent:true,body:JSON.stringify({sheetUrl:form.sheetUrl,gid:form.gid,mapping:form.mapping})});setHeaders(data.headers);setSamples(data.sampleRows);setForm(value=>({...value,mapping:data.mapping}));}catch(e){setError(e.message);}finally{setTesting(false);}}
  async function save(e){e.preventDefault();setSaving(true);setError('');try{await api('/integrations/google-sheet',{method:'PUT',body:JSON.stringify(form)});await load();}catch(e){setError(e.message);}finally{setSaving(false);}}
  async function sync(){setSyncing(true);setError('');try{await api('/integrations/google-sheet/sync',{method:'POST'});await load();}catch(e){setError(e.message);await load();}finally{setSyncing(false);}}
  const mappedCount=useMemo(()=>Object.values(form.mapping||{}).filter(Boolean).length,[form.mapping]);
  const activeUsers=users.filter(user=>user.active);const selectedUsers=form.assignmentUserIds.map(id=>activeUsers.find(user=>user.id===Number(id))).filter(Boolean);
  const savedRotation=(saved?.assignmentUserIds||[]).map(id=>activeUsers.find(user=>user.id===Number(id))).filter(Boolean);const nextAssignee=saved?.assignment_mode==='ROUND_ROBIN'&&savedRotation.length?savedRotation[Math.floor(Number(saved.assignment_cursor||0)/Math.max(1,Number(saved.leads_per_user)||1))%savedRotation.length]?.name:null;
  const toggleUser=id=>setForm(value=>({...value,assignmentUserIds:value.assignmentUserIds.includes(id)?value.assignmentUserIds.filter(userId=>userId!==id):[...value.assignmentUserIds,id]}));
  const moveUser=(index,direction)=>setForm(value=>{const ids=[...value.assignmentUserIds],next=index+direction;if(next<0||next>=ids.length)return value;[ids[index],ids[next]]=[ids[next],ids[index]];return{...value,assignmentUserIds:ids};});
  return <><div className="page-heading"><div><span className="eyebrow">Automation</span><h1>Integrations</h1><p>Automatically sync incoming Google Sheet ad leads with the CRM.</p></div><div className="integration-health"><span className={saved?.enabled?'live':'paused'}>{saved?.enabled?<><i/>Auto sync active</>:<>Auto sync paused</>}</span></div></div>{error&&<div className="alert error">{error}</div>}
  <div className="integration-grid"><main><form className="panel integration-card" onSubmit={save}><div className="integration-title"><div className="integration-logo"><FileSpreadsheet size={23}/></div><div><h2>Google Sheets Leads</h2><p>Public viewer link · Flexible column mapping · Duplicate-safe imports</p></div><a href={form.sheetUrl||'#'} target="_blank" rel="noreferrer" title="Open sheet"><ExternalLink size={16}/></a></div>
  <div className="integration-form"><label className="wide">Google Sheet URL<input required value={form.sheetUrl} onChange={e=>setForm({...form,sheetUrl:e.target.value})} placeholder="https://docs.google.com/spreadsheets/d/..."/></label><label>Sheet Tab ID (gid)<input value={form.gid} onChange={e=>setForm({...form,gid:e.target.value})}/></label><label>Sync every<select value={form.intervalMinutes} onChange={e=>setForm({...form,intervalMinutes:Number(e.target.value)})}><option value="2">2 minutes</option><option value="5">5 minutes</option><option value="10">10 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option></select></label><label>Lead Source<input value={form.defaultSource} onChange={e=>setForm({...form,defaultSource:e.target.value})}/></label><label>Assignment Method<select value={form.assignmentMode} onChange={e=>setForm({...form,assignmentMode:e.target.value})}><option value="FIXED">Fixed owner</option><option value="ROUND_ROBIN">Automatic rotation</option></select></label>{form.assignmentMode==='FIXED'&&<label>Default Owner<select value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}><option value="">Keep unassigned</option>{activeUsers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}</div>
  {form.assignmentMode==='ROUND_ROBIN'&&<section className="assignment-builder"><div className="assignment-head"><div><strong><UserRoundCheck size={16}/> Auto-assignment rotation</strong><span>Select users and arrange the order in which new leads should be assigned.</span></div><label>Leads per user<input type="number" min="1" max="1000" value={form.leadsPerUser} onChange={e=>setForm({...form,leadsPerUser:Math.max(1,Number(e.target.value)||1)})}/></label></div><div className="assignment-users">{activeUsers.map(user=><button type="button" className={form.assignmentUserIds.includes(user.id)?'selected':''} key={user.id} onClick={()=>toggleUser(user.id)}><i>{form.assignmentUserIds.indexOf(user.id)+1||'+'}</i><span>{user.name}<small>{user.designation||user.role}</small></span></button>)}</div>{selectedUsers.length>0&&<div className="assignment-order">{selectedUsers.map((user,index)=><div key={user.id}><b>{index+1}</b><span>{user.name}<small>{form.leadsPerUser} lead{Number(form.leadsPerUser)===1?'':'s'}, then next user</small></span><button type="button" title="Move up" disabled={!index} onClick={()=>moveUser(index,-1)}><ArrowUp size={14}/></button><button type="button" title="Move down" disabled={index===selectedUsers.length-1} onClick={()=>moveUser(index,1)}><ArrowDown size={14}/></button></div>)}</div>}<p className="assignment-preview">Pattern: {selectedUsers.length?selectedUsers.map(user=>`${user.name} × ${form.leadsPerUser}`).join(' → ')+' → repeat':'Select at least one user'}</p></section>}
  <div className="integration-switch"><div><strong>Automatic sync</strong><span>New rows are imported at the scheduled interval while the server is running.</span></div><button type="button" role="switch" aria-checked={form.enabled} className={form.enabled?'on':''} onClick={()=>setForm({...form,enabled:!form.enabled})}><i/></button></div>
  <div className="integration-actions"><button type="button" className="btn btn-ghost" disabled={testing||!form.sheetUrl} onClick={preview}><Cable size={15}/>{testing?'Testing...':'Test & detect columns'}</button><button className="btn btn-primary" disabled={saving}><Save size={15}/>{saving?'Saving...':'Save integration'}</button></div></form>
  {(headers.length>0||Object.keys(form.mapping).length>0)&&<section className="panel mapping-card"><div className="panel-head"><div><h2>Column Mapping</h2><p>{mappedCount} fields connected. Run Test & Detect again if a header is renamed.</p></div><span className="mapping-count">{headers.length} columns detected</span></div><div className="mapping-grid">{fields.map(field=><label key={field.key}><span>{field.label}{field.required&&<em>Recommended</em>}</span><select value={form.mapping[field.key]||''} onChange={e=>setForm({...form,mapping:{...form.mapping,[field.key]:e.target.value}})}><option value="">Not mapped</option>{headers.map(header=><option key={header}>{header}</option>)}</select></label>)}</div>{samples.length>0&&<div className="mapping-preview"><strong>Sheet preview</strong><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{samples.slice(0,3).map(row=><tr key={row.rowNumber}>{headers.map(h=><td key={h}>{row.values[h]||'—'}</td>)}</tr>)}</tbody></table></div></div>}</section>}</main>
  <aside><section className="panel sync-summary"><div className="sync-icon"><RefreshCw size={19}/></div><h2>Sync status</h2><dl><div><dt>Last attempt</dt><dd>{dateTime(saved?.last_sync_at)}</dd></div><div><dt>Last successful</dt><dd>{dateTime(saved?.last_success_at)}</dd></div><div><dt>Interval</dt><dd>{saved?.interval_minutes||form.intervalMinutes} min</dd></div>{nextAssignee&&<div><dt>Next assignee</dt><dd>{nextAssignee}</dd></div>}<div><dt>Imported total</dt><dd>{logs.reduce((sum,x)=>sum+x.imported_count,0)}</dd></div><div><dt>Updated total</dt><dd>{logs.reduce((sum,x)=>sum+(x.updated_count||0),0)}</dd></div></dl>{saved?.last_error&&<div className="sync-error"><TriangleAlert size={14}/>{saved.last_error}</div>}<button className="btn btn-primary full" disabled={syncing||!saved} onClick={sync}><RefreshCw size={15} className={syncing?'spin':''}/>{syncing?'Syncing sheet...':'Sync now'}</button></section><section className="panel integration-note"><ShieldCheck size={18}/><div><strong>Duplicate & correction protection</strong><p>Syncing the same row again will not create a duplicate. Editing a Sheet row will update the linked CRM lead without changing its owner.</p></div></section></aside></div>
  <section className="panel sync-history"><div className="panel-head"><div><h2>Sync History</h2><p>Latest automatic and manual sync activity.</p></div></div>{logs.length?<div className="table-wrap"><table><thead><tr><th>Status</th><th>Trigger</th><th>Rows</th><th>New Leads</th><th>Updated</th><th>Unchanged</th><th>Skipped</th><th>Date & Time</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td><span className={`sync-status ${log.status.toLowerCase()}`}>{log.status==='SUCCESS'?<CheckCircle2 size={13}/>:<TriangleAlert size={13}/>} {log.status}</span></td><td>{log.trigger_type}</td><td>{log.rows_found}</td><td><strong>{log.imported_count}</strong></td><td><strong>{log.updated_count||0}</strong></td><td>{log.duplicate_count}</td><td>{log.skipped_count}</td><td><Clock3 size={13}/> {dateTime(log.created_at)}</td></tr>)}</tbody></table></div>:<div className="empty">No sync has been run yet.</div>}</section></>;
}
