import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {Download,Pencil,Plus,Printer,Save,Trash2,X} from 'lucide-react';
import {api,downloadApi} from '../api';
import {useAuth} from '../context/AuthContext';

const money=value=>Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const sellerFields=[['name','Company Name'],['address','Company Address'],['phone','Phone'],['email','Email'],['website','Website'],['gstin','GSTIN'],['pan','PAN'],['bank','Bank Name'],['branch','Bank Branch & Address'],['account','Account Number'],['ifsc','IFSC Code'],['upi','UPI ID']];
const formFrom=invoice=>{const po=invoice.po,customer=po.customer||{};return{invoiceNumber:invoice.invoiceNumber,seller:{...invoice.seller},billName:customer.billName||'',billAddress:customer.billAddress||'',gstin:customer.gstin||'',mobile:customer.mobile||'',billContact:customer.billContact||'',billContactPhone:customer.billContactPhone||'',shipName:customer.shipName||'',shipAddress:customer.shipAddress||'',shipGstin:customer.shipGstin||'',shipContact:customer.shipContact||'',shipContactPhone:customer.shipContactPhone||'',placeOfSupply:po.place_of_supply||'',taxType:po.tax_type||'IGST',gstRate:po.gst_rate??5,advanceAmount:po.advance_amount??0,items:(po.items||[]).map(item=>({...item}))};};
function Field({label,value,onChange,type='text',required=false}){return <label>{label}<input type={type} min={type==='number'?'0':undefined} required={required} value={value} onChange={event=>onChange(event.target.value)}/></label>;}

export default function Invoice({editMode=false}){
  const {id}=useParams(),navigate=useNavigate(),{can,user}=useAuth();
  const [invoice,setInvoice]=useState(null),[form,setForm]=useState(null),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function load(){try{const data=await api(`/orders/invoices/${id}`);setInvoice(data.invoice);setForm(formFrom(data.invoice));setError('');}catch(error){setError(error.message);}}
  useEffect(()=>{load();},[id]);
  useEffect(()=>{if(invoice&&editMode&&can('ACTION_INVOICES_EDIT'))setEditing(true);},[invoice,editMode,can]);
  function updateItem(index,key,value){setForm(current=>({...current,items:current.items.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item)}));}
  async function save(event){event.preventDefault();setSaving(true);setError('');try{const data=await api(`/orders/invoices/${id}`,{method:'PATCH',body:JSON.stringify(form)});setInvoice(data.invoice);setForm(formFrom(data.invoice));setEditing(false);navigate(`/invoices/${id}`,{replace:true});}catch(error){setError(error.message);}finally{setSaving(false);}}
  async function remove(){if(!window.confirm(`Delete tax invoice #${invoice.invoiceNumber}? This cannot be undone.`))return;setSaving(true);setError('');try{await api(`/orders/invoices/${id}`,{method:'DELETE'});navigate('/tax-invoices');}catch(error){setError(error.message);setSaving(false);}}
  function cancel(){setForm(formFrom(invoice));setEditing(false);navigate(`/invoices/${id}`,{replace:true});}
  if(!invoice||!form)return <div className="panel">{error||'Loading invoice...'}</div>;
  const {seller,po,invoiceNumber,date}=invoice,customer=po.customer;
  return <>
    <div className="invoice-actions"><Link to="/tax-invoices" className="btn btn-ghost">← Back</Link><div className="inline-actions">{editing?<><button className="btn btn-primary" form="invoice-edit-form" disabled={saving}><Save size={15}/>{saving?'Saving...':'Save changes'}</button><button className="btn btn-ghost" type="button" onClick={cancel}><X size={15}/>Cancel</button></>:<>{can('ACTION_INVOICES_EDIT')&&<button className="btn btn-ghost" onClick={()=>navigate(`/invoices/${id}/edit`)}><Pencil size={15}/>Edit</button>}{can('ACTION_INVOICES_DELETE')&&<button className="btn btn-danger" disabled={saving} onClick={remove}><Trash2 size={15}/>Delete</button>}<button className="btn btn-ghost" onClick={()=>window.print()}><Printer size={15}/>Print</button>{can('ACTION_ORDERS_DOWNLOAD')&&<button className="btn btn-primary" onClick={()=>downloadApi(`/orders/invoices/${id}/pdf`,`Tax-Invoice-${invoiceNumber}.pdf`)}><Download size={15}/>Download PDF</button>}</>}</div></div>
    {error&&<div className="alert error">{error}</div>}
    {editing?<form id="invoice-edit-form" className="manual-invoice-form" onSubmit={save}>
      <section className="panel"><div className="panel-head"><div><h1>Edit Tax Invoice #{invoiceNumber}</h1><p>Update all invoice, customer, shipping and tax details.</p></div></div>{user.role==='ADMIN'&&<div className="compact-fields"><Field label="Invoice Number" type="number" required value={form.invoiceNumber} onChange={value=>setForm({...form,invoiceNumber:value})}/></div>}</section>
      {user.role==='ADMIN'&&<section className="panel"><div className="panel-head"><div><h2>Our Company Details</h2><p>These changes apply only to this invoice and its PDF.</p></div></div><div className="settings-grid">{sellerFields.map(([key,label])=><label key={key} className={key==='address'||key==='branch'?'span-2':''}>{label}{key==='address'||key==='branch'?<textarea required={key==='address'} value={form.seller[key]||''} onChange={event=>setForm({...form,seller:{...form.seller,[key]:event.target.value}})}/>:<input required={key==='name'} value={form.seller[key]||''} onChange={event=>setForm({...form,seller:{...form.seller,[key]:event.target.value}})}/>}</label>)}</div></section>}
      <section className="panel"><div className="panel-head"><div><h2>Customer Details</h2></div></div><div className="invoice-form-columns"><section className="po-section"><h3>Bill To</h3><div className="compact-fields"><Field label="Business / Client Name" required value={form.billName} onChange={value=>setForm({...form,billName:value})}/><Field label="GSTIN" value={form.gstin} onChange={value=>setForm({...form,gstin:value})}/><Field label="Contact Person" value={form.billContact} onChange={value=>setForm({...form,billContact:value})}/><Field label="Contact Number" value={form.billContactPhone} onChange={value=>setForm({...form,billContactPhone:value})}/><Field label="Mobile" value={form.mobile} onChange={value=>setForm({...form,mobile:value})}/><label className="full-row">Address<textarea required value={form.billAddress} onChange={event=>setForm({...form,billAddress:event.target.value})}/></label></div></section><section className="po-section"><h3>Ship To</h3><div className="compact-fields"><Field label="Name" value={form.shipName} onChange={value=>setForm({...form,shipName:value})}/><Field label="GSTIN" value={form.shipGstin} onChange={value=>setForm({...form,shipGstin:value})}/><Field label="Contact Person" value={form.shipContact} onChange={value=>setForm({...form,shipContact:value})}/><Field label="Contact Number" value={form.shipContactPhone} onChange={value=>setForm({...form,shipContactPhone:value})}/><label className="full-row">Address<textarea value={form.shipAddress} onChange={event=>setForm({...form,shipAddress:event.target.value})}/></label></div></section></div></section>
      <section className="panel"><div className="po-section-head"><h2>Invoice Items</h2><button type="button" onClick={()=>setForm({...form,items:[...form.items,{description:'',hsn:'1806.90.10',quantity:1,rate:0}]})}><Plus size={14}/>Add item</button></div>{form.items.map((item,index)=><div className="po-item" key={index}><Field label="Description" required value={item.description} onChange={value=>updateItem(index,'description',value)}/><Field label="HSN Code" value={item.hsn} onChange={value=>updateItem(index,'hsn',value)}/><Field label="Quantity" type="number" required value={item.quantity} onChange={value=>updateItem(index,'quantity',value)}/><Field label="Rate" type="number" required value={item.rate} onChange={value=>updateItem(index,'rate',value)}/><button type="button" disabled={form.items.length===1} onClick={()=>setForm({...form,items:form.items.filter((_,itemIndex)=>itemIndex!==index)})}><Trash2 size={14}/></button></div>)}<div className="po-grid compact-tax"><Field label="Place of Supply" required value={form.placeOfSupply} onChange={value=>setForm({...form,placeOfSupply:value})}/><label>Tax Type<select value={form.taxType} onChange={event=>setForm({...form,taxType:event.target.value})}><option value="IGST">IGST</option><option value="CGST_SGST">CGST + SGST</option></select></label><Field label="GST Rate (%)" type="number" required value={form.gstRate} onChange={value=>setForm({...form,gstRate:value})}/><Field label="Advance Amount" type="number" value={form.advanceAmount} onChange={value=>setForm({...form,advanceAmount:value})}/></div><div className="inline-actions form-actions"><button className="btn btn-primary" disabled={saving}><Save size={15}/>{saving?'Saving...':'Save changes'}</button><button type="button" className="btn btn-ghost" onClick={cancel}>Cancel</button></div></section>
    </form>:<article className="invoice-sheet"><header><div><h1>GST TAX INVOICE</h1><h2>{seller.name}</h2><p>{seller.address}</p><p>Ph: {seller.phone} · {seller.email}</p></div><div className="invoice-meta"><p><span>Date</span><strong>{new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(date))}</strong></p><p><span>Invoice No.</span><strong>{invoiceNumber}</strong></p><p><span>PO No.</span><strong>{po.po_number}</strong></p><p><span>GSTIN</span><strong>{seller.gstin}</strong></p><p><span>PAN</span><strong>{seller.pan}</strong></p></div></header><div className="supply-line">Place of Supply: <strong>{po.place_of_supply}</strong></div><section className="invoice-parties"><div><span>Bill To</span><h3>{customer.billName}</h3><p>{customer.billAddress}</p><p><strong>GSTIN:</strong> {customer.gstin||'-'}</p><p><strong>Mobile:</strong> {customer.mobile||'-'}</p></div><div><span>Ship To</span><h3>{customer.shipName}</h3><p>{customer.shipAddress}</p><p><strong>GSTIN:</strong> {customer.shipGstin||'-'}</p></div></section><table className="invoice-items"><thead><tr><th>S No.</th><th>Description</th><th>HSN Code</th><th>Quantity</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{po.items.map((item,index)=><tr key={index}><td>{index+1}</td><td>{item.description}</td><td>{item.hsn}</td><td>{item.quantity}</td><td>₹{money(item.rate)}</td><td>₹{money(item.quantity*item.rate)}</td></tr>)}</tbody></table><section className="invoice-totals"><div/><dl><div><dt>Subtotal</dt><dd>₹{money(po.subtotal)}</dd></div>{po.tax_type==='CGST_SGST'?<><div><dt>CGST ({po.gst_rate/2}%)</dt><dd>₹{money(po.tax_amount/2)}</dd></div><div><dt>SGST ({po.gst_rate/2}%)</dt><dd>₹{money(po.tax_amount/2)}</dd></div></>:<div><dt>IGST ({po.gst_rate}%)</dt><dd>₹{money(po.tax_amount)}</dd></div>}<div className="grand"><dt>Total</dt><dd>₹{money(po.total)}</dd></div><div><dt>Advance Amount</dt><dd>₹{money(po.advance_amount)}</dd></div><div><dt>Pending Amount</dt><dd>₹{money(po.pending_amount)}</dd></div></dl></section><footer><div><h3>Bank Details</h3><p>UPI: {seller.upi}</p><p>{seller.bank} · A/c: {seller.account} · IFSC: {seller.ifsc}</p><ol><li>Cheque / Draft to be drawn in favour of “CHOCO MANUALART”.</li><li>All disputes subject to Delhi Jurisdiction.</li><li>Payment terms — 100% advance payment.</li></ol></div><div className="signature">For {seller.name}<span>Authorised Signatory</span></div></footer></article>}
  </>;
}
