import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {RotateCcw,Search,UserX} from 'lucide-react';
import {api} from '../api';
import {useAuth} from '../context/AuthContext';
import LeadActions from '../components/LeadActions';
import {SortableTh,useSortedRows} from '../components/SortableTable';

const fmt=value=>value?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'-';

export default function NotInterestedLeads(){
  const {user,can}=useAuth();const [leads,setLeads]=useState([]);const [q,setQ]=useState('');const [error,setError]=useState('');const [restoring,setRestoring]=useState(null);
  async function load(){try{const params=new URLSearchParams({status:'NOT_INTERESTED'});if(q)params.set('q',q);const data=await api(`/leads?${params}`);setLeads(data.leads);}catch(e){setError(e.message);}}
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[q]);
  async function restore(lead){setRestoring(lead.id);setError('');try{await api(`/leads/${lead.id}`,{method:'PATCH',body:JSON.stringify({status:'CONTACTED'})});await load();}catch(e){setError(e.message);}finally{setRestoring(null);}}
  const sorted=useSortedRows(leads,'updated_at','desc');const totalValue=useMemo(()=>leads.reduce((sum,lead)=>sum+Number(lead.estimated_value||0),0),[leads]);
  return <><div className="page-heading"><div><span className="eyebrow">Lead Archive</span><h1>Not Interested Leads</h1><p>Leads marked Not Interested are kept here and hidden from the main Leads page.</p></div><Link className="btn btn-ghost" to="/leads">Back to Leads</Link></div>{error&&<div className="alert error">{error}</div>}<div className="not-interested-stats"><div><UserX size={18}/><span>Archived Leads<strong>{leads.length}</strong></span></div><div><span>Estimated Value<strong>₹{totalValue.toLocaleString('en-IN')}</strong></span></div></div><section className="panel"><div className="archive-toolbar"><div><Search size={15}/><input placeholder="Search name, company, phone or requirement..." value={q} onChange={e=>setQ(e.target.value)}/></div><span>{leads.length} result{leads.length===1?'':'s'}</span></div><div className="table-wrap"><table className="not-interested-table"><thead><tr><SortableTh label="Lead / Company" field="contact_name" sort={sorted.sort} onSort={sorted.toggle}/><SortableTh label="Contact" field="phone" sort={sorted.sort} onSort={sorted.toggle}/><SortableTh label="Requirement" field="requirement" sort={sorted.sort} onSort={sorted.toggle}/><SortableTh label="Order Details" field="quantity" sort={sorted.sort} onSort={sorted.toggle}/>{user.role==='ADMIN'&&<SortableTh label="Owner" field="assigned_name" sort={sorted.sort} onSort={sorted.toggle}/>}<SortableTh label="Updated At" field="updated_at" sort={sorted.sort} onSort={sorted.toggle}/><th>Actions</th></tr></thead><tbody>{sorted.rows.map(lead=><tr key={lead.id}><td><Link className="lead-link" to={`/leads/${lead.id}`}>{lead.contact_name}</Link><span className="cell-sub">{lead.company_name||'Individual lead'}</span></td><td>{lead.phone||lead.email||'-'}<span className="cell-sub">{lead.email&&lead.phone?lead.email:lead.city||''}</span></td><td><span className="archive-requirement" title={lead.requirement||''}>{lead.requirement||'No requirement added'}</span></td><td>{lead.box_size||'Size not set'}<span className="cell-sub">Qty: {Number(lead.quantity||0).toLocaleString('en-IN')} · ₹{Number(lead.per_box_budget||0).toLocaleString('en-IN')} per box</span></td>{user.role==='ADMIN'&&<td>{lead.assigned_name||'Unassigned'}</td>}<td className="date-cell">{fmt(lead.updated_at)}</td><td><div className="row-actions"><LeadActions phone={lead.phone} compact/>{can('ACTION_LEADS_EDIT')&&<button className="btn btn-ghost btn-sm restore-lead" disabled={restoring===lead.id} onClick={()=>restore(lead)}><RotateCcw size={13}/>{restoring===lead.id?'Moving...':'Move back'}</button>}</div></td></tr>)}</tbody></table></div>{!leads.length&&<div className="empty"><UserX size={25}/><strong>No Not Interested leads</strong><span>Leads will appear here when their status is changed to Not Interested.</span></div>}</section></>;
}
