import {useEffect,useMemo,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {Download,Pencil,Plus,ReceiptText,Save,Trash2,X} from 'lucide-react';
import {api,downloadApi} from '../api';
import {useMasterOptions} from '../hooks/useMasterOptions';

const poStatuses=[['CREATED','PO Created'],['PAYMENT_PENDING','Payment Pending'],['PARTIALLY_PAID','Partially Paid'],['PAYMENT_RECEIVED','Payment Received'],['IN_PRODUCTION','In Production'],['READY_FOR_DISPATCH','Ready for Dispatch'],['DISPATCHED','Dispatched'],['DELIVERED','Delivered'],['CANCELLED','Cancelled'],['INVOICED','Invoiced']];
const statusLabel=value=>poStatuses.find(([code])=>code===value)?.[1]||String(value||'').replaceAll('_',' ');
const taxTypeFromGstin=value=>{const state=String(value||'').trim().slice(0,2);return/^\d{2}$/.test(state)?(state==='07'?'CGST_SGST':'IGST'):'';};
const formFrom=po=>{const customer=po.customer;return{billName:customer.billName||'',billAddress:customer.billAddress||'',gstin:customer.gstin||'',mobile:customer.mobile||'',billContact:customer.billContact||'',billContactPhone:customer.billContactPhone||'',shipName:customer.shipName||'',shipAddress:customer.shipAddress||'',shipGstin:customer.shipGstin||'',shipContact:customer.shipContact||'',shipContactPhone:customer.shipContactPhone||'',placeOfSupply:po.place_of_supply||'',taxType:po.tax_type||'IGST',gstRate:po.gst_rate,advanceAmount:po.advance_amount,items:po.items.map(item=>({...item}))};};

export default function PurchaseOrder(){
  const masters=useMasterOptions(),{id}=useParams(),navigate=useNavigate();
  const [po,setPo]=useState(null),[form,setForm]=useState(null),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function load(){try{const data=await api(`/orders/purchase-orders/${id}`);setPo(data.purchaseOrder);setForm(formFrom(data.purchaseOrder));setError('');}catch(error){setError(error.message);}}
  useEffect(()=>{load();},[id]);
  function updateField(key,value){setForm(current=>{const next={...current,[key]:value},detected=taxTypeFromGstin(next.shipGstin||next.gstin);if(detected)next.taxType=detected;return next;});}
  function item(index,key,value){setForm(current=>({...current,items:current.items.map((row,rowIndex)=>rowIndex===index?{...row,[key]:value}:row)}));}
  async function save(){setSaving(true);setError('');try{await api(`/orders/purchase-orders/${id}`,{method:'PATCH',body:JSON.stringify(form)});await load();setEditing(false);}catch(error){setError(error.message);}finally{setSaving(false);}}
  async function updateStatus(status){if(status===po.status)return;setSaving(true);setError('');try{await api(`/orders/purchase-orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});await load();}catch(error){setError(error.message);}finally{setSaving(false);}}
  async function cancelPo(){if(!window.confirm(`Cancel ${po.po_number}? A cancelled PO cannot be converted to an invoice.`))return;try{await api(`/orders/purchase-orders/${id}/cancel`,{method:'POST'});await load();}catch(error){setError(error.message);}}
  async function invoice(){if(!window.confirm(`Create GST Tax Invoice from ${po.po_number}? After this, PO editing will be locked.`))return;try{const data=await api(`/orders/purchase-orders/${id}/invoice`,{method:'POST'});navigate(`/invoices/${data.id}`);}catch(error){setError(error.message);}}
  const calc=useMemo(()=>{if(!form)return{};const subtotal=form.items.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(item.rate||0),0),tax=subtotal*Number(form.gstRate||0)/100,total=subtotal+tax;return{subtotal,tax,total,pending:Math.max(0,total-Number(form.advanceAmount||0))};},[form]);
  if(!po||!form)return <div className="panel">{error||'Loading purchase order...'}</div>;
  const locked=!!po.invoice_id||po.status==='INVOICED',autoTax=taxTypeFromGstin(form.shipGstin||form.gstin);
  return <>
    <div className="page-heading"><div><Link className="back-link" to="/orders">← Back to PO & Invoices</Link><h1>{po.po_number}</h1><p>{po.company_name||po.contact_name} · Created {new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(po.created_at))}</p></div><div className="inline-actions"><button className="btn btn-ghost" onClick={()=>downloadApi(`/orders/purchase-orders/${id}/pdf`,`${po.po_number}.pdf`)}><Download size={15}/>Download PO PDF</button>{locked?<Link className="btn btn-primary" to={`/invoices/${po.invoice_id}`}><ReceiptText size={15}/>View Tax Invoice #{po.invoice_number}</Link>:editing?<><button className="btn btn-primary" disabled={saving} onClick={save}><Save size={15}/>{saving?'Saving...':'Save changes'}</button><button className="btn btn-ghost" onClick={()=>{setForm(formFrom(po));setEditing(false);}}><X size={15}/>Cancel</button></>:<><button className="btn btn-ghost" onClick={()=>setEditing(true)}><Pencil size={15}/>Edit PO</button><button className="btn btn-primary" onClick={invoice}><ReceiptText size={15}/>Create Tax Invoice</button></>}</div></div>
    {error&&<div className="alert error">{error}</div>}{locked&&<div className="po-lock-note">This PO is locked because its Tax Invoice has been created.</div>}
    <section className={`panel po-view ${editing?'inline-editing':''}`}><div className="po-view-head"><div><span>Purchase Order</span><strong>{po.po_number}</strong></div><span className={`document-status ${po.status==='CANCELLED'?'cancelled':locked?'invoiced':''}`}>{statusLabel(po.status)}</span></div>{!locked&&<div className="po-status-tracker"><div><strong>PO Tracking Status</strong><small>Update payment and fulfilment progress as the order moves ahead.</small></div><select value={po.status} disabled={saving} onChange={event=>updateStatus(event.target.value)}>{poStatuses.filter(([code])=>code!=='INVOICED').map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></div>}
      <div className="po-party-view"><div><h3>Bill To</h3><label>Name{editing?<input value={form.billName} onChange={event=>updateField('billName',event.target.value)}/>:<strong>{form.billName||'-'}</strong>}</label><label>Address{editing?<textarea value={form.billAddress} onChange={event=>updateField('billAddress',event.target.value)}/>:<p>{form.billAddress||'-'}</p>}</label><label>GSTIN{editing?<input value={form.gstin} onChange={event=>updateField('gstin',event.target.value.toUpperCase())}/>:<strong>{form.gstin||'-'}</strong>}</label><label>Contact Person{editing?<input value={form.billContact} onChange={event=>updateField('billContact',event.target.value)}/>:<strong>{form.billContact||'-'}</strong>}</label><label>Contact Number{editing?<input value={form.billContactPhone} onChange={event=>updateField('billContactPhone',event.target.value)}/>:<strong>{form.billContactPhone||'-'}</strong>}</label><label>Mobile{editing?<input value={form.mobile} onChange={event=>updateField('mobile',event.target.value)}/>:<strong>{form.mobile||'-'}</strong>}</label></div><div><h3>Ship To</h3><label>Name{editing?<input value={form.shipName} onChange={event=>updateField('shipName',event.target.value)}/>:<strong>{form.shipName||'-'}</strong>}</label><label>Address{editing?<textarea value={form.shipAddress} onChange={event=>updateField('shipAddress',event.target.value)}/>:<p>{form.shipAddress||'-'}</p>}</label><label>GSTIN{editing?<input value={form.shipGstin} onChange={event=>updateField('shipGstin',event.target.value.toUpperCase())}/>:<strong>{form.shipGstin||'-'}</strong>}</label><label>Contact Person{editing?<input value={form.shipContact} onChange={event=>updateField('shipContact',event.target.value)}/>:<strong>{form.shipContact||'-'}</strong>}</label><label>Contact Number{editing?<input value={form.shipContactPhone} onChange={event=>updateField('shipContactPhone',event.target.value)}/>:<strong>{form.shipContactPhone||'-'}</strong>}</label><label>Place of Supply{editing?<input value={form.placeOfSupply} onChange={event=>updateField('placeOfSupply',event.target.value)}/>:<strong>{form.placeOfSupply||'-'}</strong>}</label></div></div>
      <div className="po-view-items"><div className="po-section-head"><h3>Items</h3>{editing&&<button onClick={()=>setForm({...form,items:[...form.items,{description:'',hsn:'1806.90.10',quantity:1,rate:0}]})}><Plus size={14}/>Add item</button>}</div><div className="table-wrap"><table><thead><tr><th>Description</th><th>HSN Code</th><th>Quantity</th><th>Rate / Box</th><th>Amount</th>{editing&&<th/>}</tr></thead><tbody>{form.items.map((row,index)=><tr key={index}><td>{editing?<input value={row.description} onChange={event=>item(index,'description',event.target.value)}/>:row.description}</td><td>{editing?<select value={row.hsn} onChange={event=>item(index,'hsn',event.target.value)}>{(masters.HSN_CODE||[]).map(option=><option key={option.code} value={option.label}>{option.label}</option>)}</select>:row.hsn}</td><td>{editing?<input type="number" min="1" value={row.quantity} onChange={event=>item(index,'quantity',event.target.value)}/>:row.quantity}</td><td>{editing?<input type="number" min="0" value={row.rate} onChange={event=>item(index,'rate',event.target.value)}/>:<>₹{Number(row.rate).toLocaleString('en-IN')}</>}</td><td>₹{Number(row.quantity*row.rate).toLocaleString('en-IN')}</td>{editing&&<td><button className="delete-lead-btn" disabled={form.items.length===1} onClick={()=>setForm({...form,items:form.items.filter((_,itemIndex)=>itemIndex!==index)})}><Trash2 size={14}/></button></td>}</tr>)}</tbody></table></div></div>
      <div className="po-view-bottom"><div className="po-tax-fields"><label>Tax Type {autoTax&&<small>(auto from GSTIN)</small>}{editing?<select value={form.taxType} disabled={!!autoTax} onChange={event=>updateField('taxType',event.target.value)}>{(masters.TAX_TYPE||[]).map(option=><option key={option.code} value={option.code}>{option.label}</option>)}</select>:<strong>{form.taxType==='CGST_SGST'?'CGST + SGST':'IGST'}</strong>}</label><label>GST Rate{editing?<select value={form.gstRate} onChange={event=>updateField('gstRate',event.target.value)}>{(masters.GST_RATE||[]).map(option=><option key={option.code} value={option.code}>{option.label}</option>)}</select>:<strong>{form.gstRate}%</strong>}</label><label>Advance{editing?<input type="number" min="0" value={form.advanceAmount} onChange={event=>updateField('advanceAmount',event.target.value)}/>:<strong>₹{Number(form.advanceAmount).toLocaleString('en-IN')}</strong>}</label></div><dl><div><dt>Subtotal</dt><dd>₹{calc.subtotal.toLocaleString('en-IN')}</dd></div><div><dt>GST</dt><dd>₹{calc.tax.toLocaleString('en-IN')}</dd></div><div><dt>Total</dt><dd>₹{calc.total.toLocaleString('en-IN')}</dd></div><div><dt>Pending</dt><dd>₹{calc.pending.toLocaleString('en-IN')}</dd></div></dl></div>{!locked&&po.status!=='CANCELLED'&&<div className="inline-actions form-actions"><button className="btn btn-danger" onClick={cancelPo}>Cancel PO</button></div>}</section>
  </>;
}
