import {Router} from 'express';import {queryAll,queryOne} from '../db.js';import {authRequired} from '../middleware/auth.js';import {requirePermission} from '../permissions.js';import {asyncHandler} from '../utils/asyncHandler.js';
const router=Router();router.use(authRequired,requirePermission('PAGE_DASHBOARD'));
router.get('/',asyncHandler(async(req,res)=>{const {start,end,analyticsStart=start,analyticsEnd=end}=req.query;if(!start||!end)return res.status(400).json({message:'start and end are required'});const scopeSql=req.user.role==='ADMIN'?'1=1':'l.assigned_to=?',scopeParams=req.user.role==='ADMIN'?[]:[req.user.id],active=`(${scopeSql}) AND l.status<>'NOT_INTERESTED'`;const [leadStats,schedule,orderSummary,invoices,recentOrders]=await Promise.all([
queryOne(`SELECT
COUNT(CASE WHEN l.status<>'NOT_INTERESTED' THEN 1 END) total,
COUNT(CASE WHEN l.status='NOT_INTERESTED' THEN 1 END) notInterested,
COUNT(CASE WHEN l.status NOT IN ('NOT_INTERESTED','CLOSED_WON','CLOSED_LOST') THEN 1 END) open,
COUNT(CASE WHEN l.status<>'NOT_INTERESTED' AND l.next_followup_at>=? AND l.next_followup_at<? THEN 1 END) today,
COUNT(CASE WHEN l.status NOT IN ('NOT_INTERESTED','CLOSED_WON','CLOSED_LOST') AND l.next_followup_at<? THEN 1 END) overdue,
COUNT(CASE WHEN l.status<>'NOT_INTERESTED' AND l.assigned_to IS NULL THEN 1 END) unassigned,
COUNT(CASE WHEN l.status<>'NOT_INTERESTED' AND l.sample_sent=1 AND datetime(l.sample_sent_at)>=datetime(?) AND datetime(l.sample_sent_at)<datetime(?) THEN 1 END) samplesSent
FROM leads l WHERE ${scopeSql}`,[start,end,start,analyticsStart,analyticsEnd,...scopeParams]),queryAll(`SELECT l.*,u.name assigned_name FROM leads l LEFT JOIN users u ON u.id=l.assigned_to WHERE ${active} AND l.next_followup_at>=? AND l.next_followup_at<? ORDER BY l.next_followup_at LIMIT 100`,[...scopeParams,start,end]),queryOne(`SELECT COUNT(*) final_orders,COALESCE(SUM(p.total),0) order_value,COALESCE(SUM(p.advance_amount),0) payment_received,COALESCE(SUM(p.pending_amount),0) pending_payment,COALESCE(AVG(p.total),0) average_order_value FROM purchase_orders p JOIN leads l ON l.id=p.lead_id WHERE ${scopeSql} AND p.status<>'CANCELLED' AND datetime(p.created_at)>=datetime(?) AND datetime(p.created_at)<datetime(?)`,[...scopeParams,analyticsStart,analyticsEnd]),queryOne(`SELECT COUNT(*) count,COALESCE(SUM(p.total),0) value FROM tax_invoices i JOIN purchase_orders p ON p.id=i.purchase_order_id JOIN leads l ON l.id=p.lead_id WHERE ${scopeSql} AND datetime(i.created_at)>=datetime(?) AND datetime(i.created_at)<datetime(?)`,[...scopeParams,analyticsStart,analyticsEnd]),queryAll(`SELECT p.id,p.po_number,p.total,p.advance_amount,p.pending_amount,p.created_at,p.status,l.id lead_id,l.contact_name,l.company_name,u.name owner_name,i.invoice_number FROM purchase_orders p JOIN leads l ON l.id=p.lead_id LEFT JOIN users u ON u.id=l.assigned_to LEFT JOIN tax_invoices i ON i.purchase_order_id=p.id WHERE ${scopeSql} AND datetime(p.created_at)>=datetime(?) AND datetime(p.created_at)<datetime(?) ORDER BY datetime(p.created_at) DESC LIMIT 10`,[...scopeParams,analyticsStart,analyticsEnd])]);const {total,notInterested,open,today,overdue,unassigned,samplesSent}=Object.fromEntries(Object.entries(leadStats).map(([key,value])=>[key,Number(value||0)]));const orderValue=Number(orderSummary?.order_value||0),received=Number(orderSummary?.payment_received||0);res.json({stats:{total,open,today,overdue,unassigned,notInterested},schedule,analytics:{...orderSummary,samples_sent:samplesSent,invoices_created:Number(invoices?.count||0),invoiced_value:Number(invoices?.value||0),collection_rate:orderValue?Math.round(received/orderValue*100):0},recentOrders});}));
export default router;
