import {Router} from 'express';
import db from '../db.js';
import {authRequired,adminOnly} from '../middleware/auth.js';
import {fields,parseSheetUrl,readSheet,resolveMapping,syncIntegration} from '../services/sheetSync.js';

const router=Router();router.use(authRequired,adminOnly);
const getIntegration=()=>db.prepare('SELECT * FROM sheet_integrations ORDER BY id LIMIT 1').get();
const parseIds=value=>{try{return JSON.parse(value||'[]').map(Number).filter(Number.isInteger);}catch{return[];}};
const present=row=>row?{...row,enabled:Boolean(row.enabled),mapping:JSON.parse(row.mapping_json||'{}'),assignmentUserIds:parseIds(row.assignment_user_ids_json),mapping_json:undefined,assignment_user_ids_json:undefined}:null;

router.get('/google-sheet',(req,res)=>{const integration=getIntegration();const logs=integration?db.prepare('SELECT * FROM sheet_sync_logs WHERE integration_id=? ORDER BY id DESC LIMIT 20').all(integration.id):[];res.json({integration:present(integration),logs,fields});});
router.post('/google-sheet/preview',async(req,res)=>{try{const parsed=parseSheetUrl(req.body?.sheetUrl||getIntegration()?.sheet_url);const temp={sheet_id:parsed.id,gid:req.body?.gid??parsed.gid};const sheet=await readSheet(temp);const mapping=resolveMapping(sheet.headers,req.body?.mapping||{});res.json({headers:sheet.headers,mapping,sampleRows:sheet.rows.slice(0,5)});}catch(error){res.status(502).json({message:error.message});}});
router.put('/google-sheet',(req,res)=>{const b=req.body||{};let parsed;try{parsed=parseSheetUrl(b.sheetUrl);}catch(error){return res.status(400).json({message:error.message});}const interval=Math.min(1440,Math.max(1,Number(b.intervalMinutes)||5));const mapping=JSON.stringify(b.mapping||{});const assigned=b.assignedTo?Number(b.assignedTo):null;const mode=b.assignmentMode==='ROUND_ROBIN'?'ROUND_ROBIN':'FIXED';const requestedIds=[...new Set((Array.isArray(b.assignmentUserIds)?b.assignmentUserIds:[]).map(Number).filter(Number.isInteger))];const activeIds=new Set(db.prepare(`SELECT id FROM users WHERE active=1`).all().map(user=>user.id));const assignmentIds=requestedIds.filter(id=>activeIds.has(id));if(mode==='ROUND_ROBIN'&&!assignmentIds.length)return res.status(400).json({message:'Select at least one active user for auto-assignment'});if(assigned&&!activeIds.has(assigned))return res.status(400).json({message:'Select an active default owner'});const leadsPerUser=Math.min(1000,Math.max(1,Number.parseInt(b.leadsPerUser,10)||1));const idsJson=JSON.stringify(assignmentIds);const existing=getIntegration();const rotationChanged=!existing||existing.assignment_mode!==mode||existing.assignment_user_ids_json!==idsJson||Number(existing.leads_per_user)!==leadsPerUser;const cursor=rotationChanged?0:Number(existing?.assignment_cursor||0);if(existing)db.prepare("UPDATE sheet_integrations SET name=?,sheet_url=?,sheet_id=?,gid=?,enabled=?,interval_minutes=?,default_source=?,assigned_to=?,assignment_mode=?,assignment_user_ids_json=?,leads_per_user=?,assignment_cursor=?,mapping_json=?,updated_at=datetime('now') WHERE id=?").run(String(b.name||'Google Ads Leads').trim(),parsed.url,parsed.id,String(b.gid??parsed.gid),b.enabled?1:0,interval,String(b.defaultSource||'Google Ads').trim(),assigned,mode,idsJson,leadsPerUser,cursor,mapping,existing.id);else db.prepare('INSERT INTO sheet_integrations(name,sheet_url,sheet_id,gid,enabled,interval_minutes,default_source,assigned_to,assignment_mode,assignment_user_ids_json,leads_per_user,assignment_cursor,mapping_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(String(b.name||'Google Ads Leads').trim(),parsed.url,parsed.id,String(b.gid??parsed.gid),b.enabled?1:0,interval,String(b.defaultSource||'Google Ads').trim(),assigned,mode,idsJson,leadsPerUser,0,mapping);res.json({message:rotationChanged&&mode==='ROUND_ROBIN'?'Integration saved and assignment rotation started from the first user':'Google Sheet integration saved'});});
router.post('/google-sheet/sync',async(req,res)=>{try{const integration=getIntegration();if(!integration)return res.status(400).json({message:'Save the integration before syncing'});const result=await syncIntegration(integration,'MANUAL');res.json({...result,message:`Sync complete: ${result.imported} new, ${result.updated} updated, ${result.duplicates} unchanged`});}catch(error){res.status(502).json({message:error.message});}});

export default router;
