import {Router} from 'express';
import {db,queryAll,queryOne} from '../db.js';
import {adminOnly,authRequired} from '../middleware/auth.js';
import {asyncHandler} from '../utils/asyncHandler.js';
const router=Router();router.use(authRequired,adminOnly);
const count=async table=>Number((await queryOne(`SELECT COUNT(*) count FROM ${table}`))?.count||0);
async function snapshot(){const values=await Promise.all(['leads','followups','purchase_orders','tax_invoices','lead_notifications','sheet_imported_rows','sheet_sync_logs'].map(count));const integration=await queryOne('SELECT enabled FROM sheet_integrations ORDER BY id LIMIT 1');return{leads:values[0],followups:values[1],purchaseOrders:values[2],taxInvoices:values[3],notifications:values[4],sheetRows:values[5],syncLogs:values[6],sheetSyncEnabled:Boolean(integration?.enabled)};}
const phrases={INVOICES:'RESET INVOICES',ORDERS:'RESET ORDERS',LEADS:'RESET LEADS',ALL:'RESET ALL DATA'};
router.get('/',asyncHandler(async(req,res)=>res.json({counts:await snapshot()})));
router.post('/reset',asyncHandler(async(req,res)=>{const target=String(req.body?.target||'').toUpperCase();if(!phrases[target])return res.status(400).json({message:'Invalid reset target'});if(req.body?.confirmation!==phrases[target])return res.status(400).json({message:`Type ${phrases[target]} to confirm`});const before=await snapshot(),statements=[];
 if(target==='INVOICES'){const ids=(await queryAll('SELECT lead_id FROM purchase_orders WHERE manual_invoice=1')).map(x=>x.lead_id);statements.push('DELETE FROM tax_invoices','DELETE FROM purchase_orders WHERE manual_invoice=1');if(ids.length)statements.push({sql:`DELETE FROM leads WHERE id IN (${ids.map(()=>'?').join(',')})`,args:ids});statements.push("UPDATE purchase_orders SET status='CREATED' WHERE status='INVOICED'","UPDATE document_sequences SET next_value=10001 WHERE name='invoice'");}
 if(target==='ORDERS')statements.push('DELETE FROM tax_invoices','DELETE FROM purchase_orders',"DELETE FROM leads WHERE source IN ('Manual PO','Manual Invoice')","UPDATE document_sequences SET next_value=10001 WHERE name='invoice'","UPDATE document_sequences SET next_value=1 WHERE name='purchase_order'");
 if(target==='LEADS'||target==='ALL')statements.push('DELETE FROM tax_invoices','DELETE FROM purchase_orders','DELETE FROM leads','DELETE FROM activity_events',"UPDATE document_sequences SET next_value=10001 WHERE name='invoice'","UPDATE document_sequences SET next_value=1 WHERE name='purchase_order'");
 if(target==='ALL')statements.push('DELETE FROM sheet_imported_rows','DELETE FROM sheet_sync_logs',"UPDATE sheet_integrations SET enabled=0,assignment_cursor=0,last_sync_at=NULL,last_success_at=NULL,last_error=NULL,updated_at=datetime('now')");
 const tables=target==='INVOICES'?['tax_invoices']:target==='ORDERS'?['tax_invoices','purchase_orders']:['leads','followups','purchase_orders','tax_invoices','lead_notifications'];statements.push({sql:`DELETE FROM sqlite_sequence WHERE name IN (${tables.map(()=>'?').join(',')})`,args:tables});await db.batch(statements,'immediate');res.json({message:`${target==='ALL'?'All transactional test data':target.toLowerCase()} cleared successfully`,before,counts:await snapshot()});}));
export default router;
