import { Router } from 'express';
import db from '../db.js';
import { authRequired } from '../middleware/auth.js';
import { sendDocumentPdf } from '../pdfDocuments.js';
import { adminOnly } from '../middleware/auth.js';
import {requirePermission} from '../permissions.js';
import multer from 'multer';
import sharp from 'sharp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const router=Router();router.use(authRequired,requirePermission('PAGE_ORDERS'));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:3*1024*1024}});const assetsDir=path.join(path.dirname(fileURLToPath(import.meta.url)),'..','..','assets'),signatureFile=path.join(assetsDir,'signature.png'),logoFile=path.join(assetsDir,'chocomanualart-logo.webp');
const defaultSeller={name:'CHOCO MANUALART',address:'PLOT NO.38/39, DEEP ENCLAVE-III, VIKASH NAGAR, UTTAM NAGAR, Delhi 110059',phone:'+91 8595960755',gstin:'07AANFC8396E1Z0',pan:'AANFC8396E',email:'info@chocomanualart.com',website:'www.chocomanualart.com',bank:'ICICI Bank',branch:'Ramphal Chowk, Sector 7, Dwarka, New Delhi',account:'057105500662',ifsc:'ICIC0000571',upi:'chocomanualart.ibz@icici'};
function getSeller(){const row=db.prepare('SELECT settings_json FROM document_settings WHERE id=1').get();return row?{...defaultSeller,...JSON.parse(row.settings_json)}:defaultSeller;}
function nextNumber(name){const row=db.prepare('SELECT next_value FROM document_sequences WHERE name=?').get(name);db.prepare('UPDATE document_sequences SET next_value=next_value+1 WHERE name=?').run(name);return row.next_value;}
function getSequences(){return Object.fromEntries(db.prepare('SELECT name,next_value FROM document_sequences').all().map(row=>[row.name,row.next_value]));}
function scope(req,alias='l'){return req.user.role==='ADMIN'?{sql:'1=1',params:[]}:{sql:`${alias}.assigned_to=?`,params:[req.user.id]};}
function parse(row){return row?{...row,customer:JSON.parse(row.customer_json),items:JSON.parse(row.items_json)}:null;}
function canUse(req,row){return req.user.role==='ADMIN'||row.assigned_to===req.user.id;}
function totals(body){const items=(body.items||[]).map(x=>({description:String(x.description||'').trim(),hsn:String(x.hsn||'1806.90.10'),quantity:Math.max(0,Number(x.quantity||0)),rate:Math.max(0,Number(x.rate||0))})).filter(x=>x.description&&x.quantity);const subtotal=items.reduce((sum,x)=>sum+x.quantity*x.rate,0);const gstRate=Math.max(0,Number(body.gstRate??5));const taxAmount=subtotal*gstRate/100;const advance=Math.max(0,Number(body.advanceAmount||0));const total=subtotal+taxAmount;return{items,subtotal,gstRate,taxAmount,advance,total,pending:Math.max(0,total-advance)};}
router.use((req,res,next)=>{if(req.method==='GET'&&req.path.endsWith('/pdf'))return requirePermission('ACTION_ORDERS_DOWNLOAD')(req,res,next);if(req.method==='POST'&&(req.path.endsWith('/invoice')||req.path==='/invoices/manual'))return requirePermission('ACTION_ORDERS_INVOICE')(req,res,next);if(req.method==='POST'&&req.path.startsWith('/purchase-orders'))return requirePermission('ACTION_ORDERS_CREATE')(req,res,next);if(req.method==='PATCH'&&req.path.startsWith('/purchase-orders/')){const row=db.prepare('SELECT status FROM purchase_orders WHERE id=?').get(Number(req.path.split('/').at(-1)));if(row?.status==='CANCELLED')return res.status(409).json({message:'A cancelled purchase order cannot be edited'});}next();});

router.get('/',(req,res)=>{const s=scope(req);const eligible=db.prepare(`SELECT l.id,l.contact_name,l.company_name,l.phone,l.email,l.city,l.box_size,l.quantity,l.per_box_budget,l.estimated_value FROM leads l WHERE ${s.sql} AND l.finalized=1 AND NOT EXISTS(SELECT 1 FROM purchase_orders p WHERE p.lead_id=l.id AND p.status!='CANCELLED') ORDER BY l.updated_at DESC`).all(...s.params);const pos=db.prepare(`SELECT p.*,l.contact_name,l.company_name,l.phone,l.email,u.name owner_name,i.id invoice_id,i.invoice_number,i.created_at invoice_created_at FROM purchase_orders p JOIN leads l ON l.id=p.lead_id LEFT JOIN users u ON u.id=l.assigned_to LEFT JOIN tax_invoices i ON i.purchase_order_id=p.id WHERE ${s.sql} AND p.manual_invoice=0 ORDER BY p.id DESC`).all(...s.params).map(parse);res.json({eligible,purchaseOrders:pos,seller:{...getSeller(),hasSignature:fs.existsSync(signatureFile),hasLogo:fs.existsSync(logoFile)}});});

router.get('/invoices',(req,res)=>{const s=scope(req);const rows=db.prepare(`SELECT i.id,i.invoice_number,i.created_at,p.total,p.advance_amount,p.pending_amount,p.po_number,p.manual_invoice,l.contact_name,l.company_name,l.phone,l.email,u.name owner_name FROM tax_invoices i JOIN purchase_orders p ON p.id=i.purchase_order_id JOIN leads l ON l.id=p.lead_id LEFT JOIN users u ON u.id=l.assigned_to WHERE ${s.sql} ORDER BY i.id DESC`).all(...s.params);res.json({invoices:rows,seller:{...getSeller(),hasSignature:fs.existsSync(signatureFile),hasLogo:fs.existsSync(logoFile)},sequences:req.user.role==='ADMIN'?getSequences():undefined});});

router.get('/settings',(req,res)=>res.json({seller:{...getSeller(),hasSignature:fs.existsSync(signatureFile),hasLogo:fs.existsSync(logoFile)},sequences:req.user.role==='ADMIN'?getSequences():undefined}));
router.put('/settings',adminOnly,(req,res)=>{const seller={};for(const key of Object.keys(defaultSeller))seller[key]=String(req.body?.[key]??'').trim();if(!seller.name||!seller.address)return res.status(400).json({message:'Business name and address are required'});db.prepare(`INSERT INTO document_settings(id,settings_json,updated_at) VALUES(1,?,datetime('now')) ON CONFLICT(id) DO UPDATE SET settings_json=excluded.settings_json,updated_at=datetime('now')`).run(JSON.stringify(seller));res.json({message:'Brand and document details updated'});});
router.put('/settings/sequences',adminOnly,(req,res)=>{const purchaseOrder=Number(req.body?.purchaseOrder),invoice=Number(req.body?.invoice);if(!Number.isSafeInteger(purchaseOrder)||purchaseOrder<1||!Number.isSafeInteger(invoice)||invoice<1)return res.status(400).json({message:'PO and invoice starting numbers must be positive whole numbers'});const highestPo=db.prepare("SELECT COALESCE(MAX(CAST(SUBSTR(po_number,4) AS INTEGER)),0) value FROM purchase_orders WHERE po_number LIKE 'PO-%'").get().value;const highestInvoice=db.prepare('SELECT COALESCE(MAX(invoice_number),0) value FROM tax_invoices').get().value;if(purchaseOrder<=highestPo)return res.status(409).json({message:`Next PO number must be greater than existing PO-${String(highestPo).padStart(5,'0')}`});if(invoice<=highestInvoice)return res.status(409).json({message:`Next invoice number must be greater than existing invoice ${highestInvoice}`});const save=db.transaction(()=>{db.prepare("UPDATE document_sequences SET next_value=? WHERE name='purchase_order'").run(purchaseOrder);db.prepare("UPDATE document_sequences SET next_value=? WHERE name='invoice'").run(invoice);});save();res.json({message:'PO and invoice starting numbers updated',sequences:getSequences()});});
router.post('/settings/logo',adminOnly,upload.single('logo'),async(req,res)=>{if(!req.file)return res.status(400).json({message:'Logo image is required'});if(!['image/png','image/jpeg','image/webp'].includes(req.file.mimetype))return res.status(400).json({message:'Upload PNG, JPG or WebP logo'});fs.mkdirSync(assetsDir,{recursive:true});await sharp(req.file.buffer).resize({width:800,height:282,fit:'inside',withoutEnlargement:true}).webp().toFile(logoFile);res.json({message:'Brand logo updated successfully'});});

router.post('/settings/signature',adminOnly,upload.single('signature'),async(req,res)=>{if(!req.file)return res.status(400).json({message:'Signature image is required'});if(!['image/png','image/jpeg','image/webp'].includes(req.file.mimetype))return res.status(400).json({message:'Upload PNG, JPG or WebP signature'});fs.mkdirSync(assetsDir,{recursive:true});await sharp(req.file.buffer).trim().resize({width:400,height:180,fit:'inside',withoutEnlargement:true}).png().toFile(signatureFile);res.json({message:'Authorised signature updated successfully'});});

router.post('/purchase-orders/manual',(req,res)=>{const b=req.body||{};const amount=totals(b);if(!b.billName?.trim())return res.status(400).json({message:'Billing name is required'});if(!amount.items.length)return res.status(400).json({message:'Add at least one valid item'});const create=db.transaction(()=>{const leadResult=db.prepare(`INSERT INTO leads(company_name,contact_name,phone,email,city,source,requirement,box_size,quantity,per_box_budget,estimated_value,status,assigned_to,finalized,finalized_at,created_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, ?,datetime('now'))`).run(b.billName.trim(),String(b.billContact||b.billName).trim(),b.billContactPhone||b.mobile||null,b.email||null,b.placeOfSupply||null,'Manual PO',amount.items.map(x=>x.description).join(', '),null,amount.items.reduce((sum,x)=>sum+x.quantity,0),0,amount.total,'ORDER_CONFIRMED',req.user.id,1,new Date().toISOString(),req.user.id);const leadId=leadResult.lastInsertRowid;const customer={billName:b.billName.trim(),billAddress:b.billAddress||'',gstin:b.gstin||'',mobile:b.mobile||'',billContact:b.billContact||b.billName,billContactPhone:b.billContactPhone||b.mobile||'',shipName:b.shipName||b.billName,shipAddress:b.shipAddress||b.billAddress||'',shipGstin:b.shipGstin||b.gstin||'',shipContact:b.shipContact||b.billContact||b.billName,shipContactPhone:b.shipContactPhone||b.billContactPhone||b.mobile||''};const next=nextNumber('purchase_order');const poNumber=`PO-${String(next).padStart(5,'0')}`;const result=db.prepare(`INSERT INTO purchase_orders(po_number,lead_id,customer_json,items_json,place_of_supply,subtotal,gst_rate,tax_type,tax_amount,total,advance_amount,pending_amount,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(poNumber,leadId,JSON.stringify(customer),JSON.stringify(amount.items),b.placeOfSupply||'',amount.subtotal,amount.gstRate,b.taxType==='CGST_SGST'?'CGST_SGST':'IGST',amount.taxAmount,amount.total,amount.advance,amount.pending,req.user.id);return{id:result.lastInsertRowid,poNumber};});const result=create();res.status(201).json({id:result.id,message:`Manual purchase order ${result.poNumber} created`});});

router.post('/purchase-orders',(req,res)=>{const b=req.body||{};const lead=db.prepare('SELECT * FROM leads WHERE id=?').get(Number(b.leadId));if(!lead)return res.status(404).json({message:'Lead not found'});if(req.user.role!=='ADMIN'&&lead.assigned_to!==req.user.id)return res.status(403).json({message:'You cannot create a PO for this lead'});if(!lead.finalized)return res.status(400).json({message:'Only finalized leads can be converted to a PO'});if(db.prepare('SELECT id FROM purchase_orders WHERE lead_id=?').get(lead.id))return res.status(409).json({message:'A PO already exists for this lead'});const items=(b.items||[]).map(x=>({description:String(x.description||'').trim(),hsn:String(x.hsn||'1806.90.10'),quantity:Math.max(0,Number(x.quantity||0)),rate:Math.max(0,Number(x.rate||0))})).filter(x=>x.description&&x.quantity);if(!items.length)return res.status(400).json({message:'Add at least one valid item'});const subtotal=items.reduce((sum,x)=>sum+x.quantity*x.rate,0);const gstRate=Math.max(0,Number(b.gstRate??5));const taxAmount=subtotal*gstRate/100;const advance=Math.max(0,Number(b.advanceAmount||0));const total=subtotal+taxAmount;const customer={billName:b.billName||lead.company_name||lead.contact_name,billAddress:b.billAddress||lead.city||'',gstin:b.gstin||'',mobile:b.mobile||lead.phone||'',billContact:b.billContact||lead.contact_name||'',billContactPhone:b.billContactPhone||lead.phone||'',shipName:b.shipName||b.billName||lead.company_name||lead.contact_name,shipAddress:b.shipAddress||b.billAddress||lead.city||'',shipGstin:b.shipGstin||b.gstin||'',shipContact:b.shipContact||b.billContact||lead.contact_name||'',shipContactPhone:b.shipContactPhone||b.billContactPhone||lead.phone||''};const next=nextNumber('purchase_order');const poNumber=`PO-${String(next).padStart(5,'0')}`;const result=db.prepare(`INSERT INTO purchase_orders(po_number,lead_id,customer_json,items_json,place_of_supply,subtotal,gst_rate,tax_type,tax_amount,total,advance_amount,pending_amount,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(poNumber,lead.id,JSON.stringify(customer),JSON.stringify(items),b.placeOfSupply||'',subtotal,gstRate,b.taxType==='CGST_SGST'?'CGST_SGST':'IGST',taxAmount,total,advance,Math.max(0,total-advance),req.user.id);res.status(201).json({id:result.lastInsertRowid,message:`Purchase order ${poNumber} created`});});

router.get('/purchase-orders/:id',(req,res)=>{const row=db.prepare(`SELECT p.*,l.contact_name,l.company_name,l.assigned_to,i.id invoice_id,i.invoice_number FROM purchase_orders p JOIN leads l ON l.id=p.lead_id LEFT JOIN tax_invoices i ON i.purchase_order_id=p.id WHERE p.id=?`).get(Number(req.params.id));if(!row)return res.status(404).json({message:'Purchase order not found'});if(!canUse(req,row))return res.status(403).json({message:'You cannot access this PO'});res.json({purchaseOrder:parse(row),seller:getSeller()});});

router.get('/purchase-orders/:id/pdf',async(req,res)=>{const row=db.prepare(`SELECT p.*,l.assigned_to FROM purchase_orders p JOIN leads l ON l.id=p.lead_id WHERE p.id=?`).get(Number(req.params.id));if(!row)return res.status(404).json({message:'Purchase order not found'});if(!canUse(req,row))return res.status(403).json({message:'You cannot access this PO'});await sendDocumentPdf(res,{type:'PURCHASE ORDER',number:row.po_number,date:row.created_at,po:parse(row),seller:getSeller()});});

router.patch('/purchase-orders/:id',(req,res)=>{const row=db.prepare(`SELECT p.*,l.assigned_to FROM purchase_orders p JOIN leads l ON l.id=p.lead_id WHERE p.id=?`).get(Number(req.params.id));if(!row)return res.status(404).json({message:'Purchase order not found'});if(!canUse(req,row))return res.status(403).json({message:'You cannot update this PO'});if(row.status==='INVOICED'||db.prepare('SELECT id FROM tax_invoices WHERE purchase_order_id=?').get(row.id))return res.status(409).json({message:'Invoiced PO is locked and cannot be changed'});const b=req.body||{};const amount=totals(b);if(!amount.items.length)return res.status(400).json({message:'Add at least one valid item'});const customer={billName:b.billName||'',billAddress:b.billAddress||'',gstin:b.gstin||'',mobile:b.mobile||'',billContact:b.billContact||'',billContactPhone:b.billContactPhone||'',shipName:b.shipName||b.billName||'',shipAddress:b.shipAddress||b.billAddress||'',shipGstin:b.shipGstin||b.gstin||'',shipContact:b.shipContact||b.billContact||'',shipContactPhone:b.shipContactPhone||b.billContactPhone||''};db.prepare(`UPDATE purchase_orders SET customer_json=?,items_json=?,place_of_supply=?,subtotal=?,gst_rate=?,tax_type=?,tax_amount=?,total=?,advance_amount=?,pending_amount=? WHERE id=?`).run(JSON.stringify(customer),JSON.stringify(amount.items),b.placeOfSupply||'',amount.subtotal,amount.gstRate,b.taxType==='CGST_SGST'?'CGST_SGST':'IGST',amount.taxAmount,amount.total,amount.advance,amount.pending,row.id);res.json({message:`Purchase order ${row.po_number} updated`});});

router.post('/purchase-orders/:id/invoice',(req,res)=>{const po=db.prepare(`SELECT p.*,l.assigned_to FROM purchase_orders p JOIN leads l ON l.id=p.lead_id WHERE p.id=?`).get(Number(req.params.id));if(!po)return res.status(404).json({message:'Purchase order not found'});if(req.user.role!=='ADMIN'&&po.assigned_to!==req.user.id)return res.status(403).json({message:'You cannot invoice this PO'});if(po.status==='CANCELLED')return res.status(409).json({message:'A cancelled purchase order cannot be converted'});const existing=db.prepare('SELECT id,invoice_number FROM tax_invoices WHERE purchase_order_id=?').get(po.id);if(existing)return res.status(409).json({message:`Invoice ${existing.invoice_number} already exists`});const tx=db.transaction(()=>{const number=nextNumber('invoice'),currentSeller=getSeller();const snapshot={seller:currentSeller,po:parse(po),invoiceNumber:number,date:new Date().toISOString()};const result=db.prepare('INSERT INTO tax_invoices(invoice_number,purchase_order_id,invoice_json,created_by) VALUES(?,?,?,?)').run(number,po.id,JSON.stringify(snapshot),req.user.id);db.prepare("UPDATE purchase_orders SET status='INVOICED' WHERE id=?").run(po.id);return{id:result.lastInsertRowid,number};});const invoice=tx();res.status(201).json({id:invoice.id,invoiceNumber:invoice.number,message:`Tax invoice ${invoice.number} created`});});

router.post('/purchase-orders/:id/cancel',(req,res)=>{const row=db.prepare(`SELECT p.*,l.assigned_to FROM purchase_orders p JOIN leads l ON l.id=p.lead_id WHERE p.id=?`).get(Number(req.params.id));if(!row)return res.status(404).json({message:'Purchase order not found'});if(!canUse(req,row))return res.status(403).json({message:'You cannot cancel this PO'});if(row.status==='INVOICED'||db.prepare('SELECT id FROM tax_invoices WHERE purchase_order_id=?').get(row.id))return res.status(409).json({message:'An invoiced purchase order cannot be cancelled'});db.prepare("UPDATE purchase_orders SET status='CANCELLED' WHERE id=?").run(row.id);res.json({message:`Purchase order ${row.po_number} cancelled`});});

router.post('/invoices/manual',(req,res)=>{const b=req.body||{},amount=totals(b);if(!b.billName?.trim())return res.status(400).json({message:'Billing name is required'});if(!amount.items.length)return res.status(400).json({message:'Add at least one valid item'});const create=db.transaction(()=>{const invoiceNumber=nextNumber('invoice'),now=new Date().toISOString();const leadResult=db.prepare(`INSERT INTO leads(company_name,contact_name,phone,email,city,source,requirement,quantity,estimated_value,status,assigned_to,finalized,finalized_at,created_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,datetime('now'))`).run(b.billName.trim(),String(b.billContact||b.billName).trim(),b.billContactPhone||b.mobile||null,b.email||null,b.placeOfSupply||null,'Manual Invoice',amount.items.map(item=>item.description).join(', '),amount.items.reduce((sum,item)=>sum+item.quantity,0),amount.total,'ORDER_CONFIRMED',req.user.id,1,now,req.user.id);const customer={billName:b.billName.trim(),billAddress:b.billAddress||'',gstin:b.gstin||'',mobile:b.mobile||'',billContact:b.billContact||b.billName,billContactPhone:b.billContactPhone||b.mobile||'',shipName:b.shipName||b.billName,shipAddress:b.shipAddress||b.billAddress||'',shipGstin:b.shipGstin||b.gstin||'',shipContact:b.shipContact||b.billContact||b.billName,shipContactPhone:b.shipContactPhone||b.billContactPhone||b.mobile||''};const poNumber=`MI-${invoiceNumber}`;const poResult=db.prepare(`INSERT INTO purchase_orders(po_number,lead_id,customer_json,items_json,place_of_supply,subtotal,gst_rate,tax_type,tax_amount,total,advance_amount,pending_amount,status,created_by,manual_invoice) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)`).run(poNumber,leadResult.lastInsertRowid,JSON.stringify(customer),JSON.stringify(amount.items),b.placeOfSupply||'',amount.subtotal,amount.gstRate,b.taxType==='CGST_SGST'?'CGST_SGST':'IGST',amount.taxAmount,amount.total,amount.advance,amount.pending,'INVOICED',req.user.id);const po={id:poResult.lastInsertRowid,po_number:'Manual Invoice',lead_id:leadResult.lastInsertRowid,customer,items:amount.items,place_of_supply:b.placeOfSupply||'',subtotal:amount.subtotal,gst_rate:amount.gstRate,tax_type:b.taxType==='CGST_SGST'?'CGST_SGST':'IGST',tax_amount:amount.taxAmount,total:amount.total,advance_amount:amount.advance,pending_amount:amount.pending,status:'INVOICED'};const snapshot={seller:getSeller(),po,invoiceNumber,date:now};const result=db.prepare('INSERT INTO tax_invoices(invoice_number,purchase_order_id,invoice_json,created_by) VALUES(?,?,?,?)').run(invoiceNumber,poResult.lastInsertRowid,JSON.stringify(snapshot),req.user.id);return{id:result.lastInsertRowid,number:invoiceNumber};});const invoice=create();res.status(201).json({id:invoice.id,invoiceNumber:invoice.number,message:`Manual tax invoice ${invoice.number} created`});});

router.get('/invoices/:id',(req,res)=>{const row=db.prepare(`SELECT i.*,p.lead_id,l.assigned_to FROM tax_invoices i JOIN purchase_orders p ON p.id=i.purchase_order_id JOIN leads l ON l.id=p.lead_id WHERE i.id=?`).get(Number(req.params.id));if(!row)return res.status(404).json({message:'Invoice not found'});if(req.user.role!=='ADMIN'&&row.assigned_to!==req.user.id)return res.status(403).json({message:'You cannot access this invoice'});res.json({invoice:{id:row.id,...JSON.parse(row.invoice_json)}});});

router.get('/invoices/:id/pdf',async(req,res)=>{const row=db.prepare(`SELECT i.*,l.assigned_to FROM tax_invoices i JOIN purchase_orders p ON p.id=i.purchase_order_id JOIN leads l ON l.id=p.lead_id WHERE i.id=?`).get(Number(req.params.id));if(!row)return res.status(404).json({message:'Invoice not found'});if(req.user.role!=='ADMIN'&&row.assigned_to!==req.user.id)return res.status(403).json({message:'You cannot access this invoice'});const snapshot=JSON.parse(row.invoice_json);await sendDocumentPdf(res,{type:'GST TAX INVOICE',number:snapshot.invoiceNumber,date:snapshot.date,po:snapshot.po,seller:snapshot.seller});});

export default router;
